// 数独求败 v3.0.14 手机音效唤醒版
const boardEl=document.querySelector('#board'),timerEl=document.querySelector('#timer'),mistakesEl=document.querySelector('#mistakes');
const urlLang=new URLSearchParams(location.search).get('lang');
let lang=urlLang==='en'?'en':urlLang==='zh'?'zh':localStorage.getItem('sudoku-lang')||'zh';
if(urlLang==='en'||urlLang==='zh')localStorage.setItem('sudoku-lang',lang);
const levelNames={novice:'初级',intermediate:'中级',advanced:'高级',king:'王者',legend:'求败'},levelNamesEn={novice:'Beginner',intermediate:'Intermediate',advanced:'Advanced',king:'Master',legend:'Unbeaten'},levelOrder=['novice','intermediate','advanced','king','legend'];
const uiText={
  zh:{errors:'错误',time:'时间',focusTechniques:'本局重点技巧',coachWhy:'为什么？',coachDisagree:'我觉得不对',coachSimpler:'有没有更简单的突破口？',coachNext:'下一步看哪里？',ask:'问',coachPlaceholder:'和“思”聊一句，例如：我没看懂这个技巧',localCoach:'本地教练：先用当前棋盘规则解释，不联网。',erase:'擦除',notes:'标记',autoNotes:'一键标记',hint:'提示',newGame:'新游戏',keyboardTip:'提示：电脑端可使用数字键与方向键操作',completeTitle:'漂亮，完成了！',completePrefix:'你完成了这局',completeSuffix:'数独',usedTime:'用时',score:'本局得分',again:'再来一局',viewBoard:'查看棋盘',currentRank:'当前等级',wisdomPoints:'智慧点',badges:'技巧勋章',records:'个人纪录',scoreRules:'当前积分规则',rankRuleNote:'等级随积分动态升降；未达标时可试玩下一级 3 次。',recordRuleNote:'打破最佳时间或最高分纪录，可获得额外积分。',hintRuleNote:'提示与快速填充不加分；同一格每局只奖励一次。',expressFill:'快速填充',challenge:'本局挑战',passRate:'参考通关率仅',avgTime:'玩家平均用时',beat:'你超过了',sameLevelPlayers:'的同级玩家',usedTech:'你使用了',techniqueWord:'技巧',localData:'当前为本地参考数据',basic:'基础排除',avatarSection:'个人图案',randomAvatar:'随机',photoAvatar:'照片',applyAvatar:'应用设计',photoLocalNote:'照片仅压缩保存在本机，不会上传。',customAvatarPlaceholder:'1～2字',roundOver:'本轮结束',roundOverDesc:'已经出现 3 次错误，可以重新开局，或扣除积分继续当前棋盘。',rechargeContinue:'充值 10 元得 10000 点',restartGame:'重新开局',streakFailTitle:'连续三局失败',streakFailText:'当前等级挑战遇到瓶颈，可以降级练习，或充值保留等级。',demoteRestart:'降级并重新开始',rechargeKeepRank:'充值 10 元得 10000 点'},
  en:{errors:'Errors',time:'Time',focusTechniques:'Focus techniques',coachWhy:'Why?',coachDisagree:'I disagree',coachSimpler:'Any simpler opening?',coachNext:'Where next?',ask:'Ask',coachPlaceholder:'Ask “Think”, e.g. I do not understand this technique',localCoach:'Local coach: explains from the current board, no internet.',erase:'Erase',notes:'Notes',autoNotes:'Auto notes',hint:'Hint',newGame:'New game',keyboardTip:'Tip: use number keys and arrow keys on desktop',completeTitle:'Nice, completed!',completePrefix:'You completed this ',completeSuffix:' Sudoku',usedTime:'Time',score:'Score',again:'Play again',viewBoard:'View board',currentRank:'Rank',wisdomPoints:'Points',badges:'Technique badges',records:'Records',scoreRules:'Scoring rules',rankRuleNote:'Rank changes with points; you may trial the next level 3 times before qualifying.',recordRuleNote:'New best time or high score grants extra points.',hintRuleNote:'Hints and express fill do not score; each cell scores once per game.',expressFill:'Express fill',challenge:'Challenge',passRate:'Reference clear rate only',avgTime:'average time',beat:'You beat',sameLevelPlayers:'of same-level players',usedTech:'You used',techniqueWord:'techniques',localData:'Local reference data',basic:'Basic elimination',avatarSection:'Avatar',randomAvatar:'Random',photoAvatar:'Photo',applyAvatar:'Apply',photoLocalNote:'Photos are compressed and saved locally only; nothing is uploaded.',customAvatarPlaceholder:'1–2 chars',roundOver:'Round over',roundOverDesc:'You have made 3 mistakes. Start a new puzzle, or spend points to continue this board.',rechargeContinue:'Recharge $1.99 for 10000 points',restartGame:'Restart',streakFailTitle:'Three failures in a row',streakFailText:'This rank is getting tough. You can practice at a lower rank, or recharge to keep your rank.',demoteRestart:'Demote and restart',rechargeKeepRank:'Recharge $1.99 for 10000 points'}
};
const techniqueI18n={nakedSingle:['唯一候选','Naked Single','排除同行、同列和宫内已有数字，只剩一个候选。','Eliminate numbers already present in the row, column, and box; only one candidate remains.'],hiddenSingle:['隐性唯一','Hidden Single','一个数字在某行、列或宫内只有一个可落脚的位置。','A number has only one possible position in a row, column, or box.'],nakedPair:['显性数对','Naked Pair','两个格子共享相同的两个候选，因此可从同一区域其他格中排除它们。','Two cells share the same two candidates, so those candidates can be removed from other cells in the unit.'],hiddenPair:['隐性数对','Hidden Pair','两个数字在同一区域内都只出现在相同两格，可删除这两格中的其他候选。','Two digits appear only in the same two cells of a unit, so other candidates in those cells can be removed.'],nakedTriple:['三数组','Naked Triple','三个格子的候选合集只有三个数字，可从同一区域其他格删除这些候选。','Three cells contain only three combined candidates; remove them from other cells in the unit.'],xWing:['X-Wing','X-Wing','某数字在两行中都只落在相同两列，可从这两列的其他位置排除该数字。','A digit appears in the same two columns across two rows; remove it from other cells in those columns.'],xyWing:['XY-Wing','XY-Wing','三个双候选格形成XY、XZ、YZ结构，可排除共同可见位置的Z候选。','Three bivalue cells form XY, XZ, and YZ; remove Z from cells seeing both wings.'],uniqueRectangle:['唯一矩形','Unique Rectangle','利用四格矩形避免形成双解，从额外候选中完成排除。','Use a four-cell rectangle to avoid a deadly pattern and eliminate extra candidates.'],aic:['强弱链 / AIC','AIC Chain','沿候选的强弱链接交替推导，通过链首尾关系排除候选。','Follow alternating strong and weak links to eliminate candidates from chain relationships.'],als:['ALS 组合','ALS Set','利用近锁定集合之间的受限公共候选进行排除。','Use almost locked sets and restricted common candidates to eliminate candidates.'],lockedCandidate:['区块排除','Locked Candidates','某数字在宫内的候选集中于同一行或列，可排除宫外候选。','A digit’s candidates in a box are locked to one row or column, so remove it outside the box.'],bugPlusOne:['全双值坟墓','BUG+1','所有未定格均为双值，仅一格为三值；用奇偶规律确定额外候选。','All unsolved cells are bivalue except one trivalue cell; parity identifies the extra candidate.']};
function T(key){return(uiText[lang]&&uiText[lang][key])||uiText.zh[key]||key}
function levelLabel(id){return lang==='en'?levelNamesEn[id]:levelNames[id]}
function techniqueName(id){return lang==='en'?(techniqueI18n[id]?.[1]||techniques[id]?.name):(techniqueI18n[id]?.[0]||techniques[id]?.name)}
function techniqueDesc(id){return lang==='en'?(techniqueI18n[id]?.[3]||techniques[id]?.desc):(techniqueI18n[id]?.[2]||techniques[id]?.desc)}
function techniqueIdByName(name){return Object.entries(techniqueI18n).find(([,v])=>v[0]===name||v[1]===name)?.[0]||null}
function routeLabel(name){const id=routeTechniqueIds?.[name]||techniqueIdByName(name);if(id)return techniqueName(id);return lang==='en'&&name==='多技巧链式推理'?'Multi-technique chain':name}
const skillTemplates={
  novice:['530608910600005340190042000859760400426050701013924806000500004280009035045080000'],
  intermediate:['504678012602190008190300007809000020000800091713920000001000200287000005005080170'],
  advanced:['000670910002005048190040500850000000420803700013024006000037004000400000040080100'],
  king:[
    '008600000000007000109000403080205000500000004600403000201000309000700000005094600',
    '000600200000007000109000403080205006500000000600403000201000309000700000005094600'
  ],
  legend:['083020090000800100029300008000098700070000060006740000300006980002005000010030540']
};
const advancedRoutes={novice:['显性唯一','显性数对'],intermediate:['隐性唯一','隐性数对','区块排除'],advanced:['区块排除','三数组','X-Wing'],king:['三数组','X-Wing','XY-Wing','唯一矩形'],legend:['X-Wing','XY-Wing','强弱链 / AIC','ALS 组合']},specialTechniqueIds=new Set(['nakedTriple','xWing','xyWing','uniqueRectangle','aic','als','lockedCandidate','bugPlusOne']);
const techniques={
  nakedSingle:{name:'唯一候选',icon:'一',points:20,desc:'排除同行、同列和宫内已有数字，只剩一个候选。'},
  hiddenSingle:{name:'隐性唯一',icon:'隐',points:30,desc:'一个数字在某行、列或宫内只有一个可落脚的位置。'},
  nakedPair:{name:'显性数对',icon:'双',points:50,desc:'两个格子共享相同的两个候选，因此可从同一区域其他格中排除它们。'},
  hiddenPair:{name:'隐性数对',icon:'隐双',points:60,desc:'两个数字在同一区域内都只出现在相同两格，可删除这两格中的其他候选。'},
  nakedTriple:{name:'三数组',icon:'三',points:70,desc:'三个格子的候选合集只有三个数字，可从同一区域其他格删除这些候选。'},
  xWing:{name:'X-Wing',icon:'X',points:90,desc:'某数字在两行中都只落在相同两列，可从这两列的其他位置排除该数字。'},
  xyWing:{name:'XY-Wing',icon:'翼',points:110,desc:'三个双候选格形成XY、XZ、YZ结构，可排除共同可见位置的Z候选。'},
  uniqueRectangle:{name:'唯一矩形',icon:'矩',points:110,desc:'利用四格矩形避免形成双解，从额外候选中完成排除。'},
  aic:{name:'强弱链 / AIC',icon:'链',points:140,desc:'沿候选的强弱链接交替推导，通过链首尾关系排除候选。'},
  als:{name:'ALS 组合',icon:'集',points:150,desc:'利用近锁定集合之间的受限公共候选进行排除。'},
  lockedCandidate:{name:'区块排除',icon:'锁',points:60,desc:'某数字在宫内的候选集中于同一行或列，可排除宫外候选。'},
  bugPlusOne:{name:'全双值坟墓',icon:'墓',points:120,desc:'所有未定格均为双值，仅一格为三值；用奇偶规律确定额外候选。'}
};
const avatars=['◈','✦','☘','月','山','水','竹','九'];
const ranks=[
  {name:'初级',min:0},{name:'中级',min:1000},{name:'高级',min:3000},{name:'王者',min:20000},{name:'求败',min:100000}
],difficultyScore={novice:1,intermediate:2,advanced:4,king:8,legend:16},requiredPlaySeconds=[0,0,0,0,0];
const featureMilestones=[{id:'expressFill',name:'高级快速填充',rankIndex:2,points:100}];
const basicTechniqueIds=new Set(['nakedSingle','hiddenSingle','nakedPair','hiddenPair']),techniqueMultipliers={lockedCandidate:[3,5],nakedTriple:[4,6],xWing:[6,8],xyWing:[7,9],uniqueRectangle:[7,9],bugPlusOne:[8,10],aic:[9,10],als:[9,10]};
const continueCost={novice:30,intermediate:60,advanced:100,king:150,legend:220};
const rechargeProduct={zhPrice:'10 元',enPrice:'$1.99',points:10000};
const autoNotesCost={advanced:1000,king:2000,legend:5000};
const playerBenchmarks={novice:{average:340,spread:70},intermediate:{average:620,spread:125},advanced:{average:940,spread:185},king:{average:1320,spread:260},legend:{average:1860,spread:360}};
const passRateRanges={novice:[78,91],intermediate:[55,72],advanced:[31,48],king:[12,24],legend:[5,11]};
let solution=[],puzzle=[],values=[],notes=[],selected=null,level='novice',mistakes=0,hints=3,seconds=0,timerId=null,finished=false,toastTimer,noteMode=false,activeNoteNumber=null,selectedPadNumber=null,expressFinishing=false,lastFinalRunAt=0,correctStreak=0,initialEmptyCount=0,journeyMoments=new Set(),lastCoachContext=null,currentPassRate=null;
let noteInputMode=null;
let profile=loadProfile(),pendingBadge=null,scoredCells=new Set(),gameTechniques=new Set(),rewardedGameTechniques=new Set(),completionAwarded=false,currentGameIsTrial=false,gameScore=0,completionRecord=null;
profile.lastPlayedLevel=profile.lastPlayedLevel||null;
let selectedRouteTechnique=null;
const toggleCandidateSet=globalThis.SudokuNoteUtils?.toggleCandidateSet||((existing,digit)=>{const next=new Set(existing||[]);next.has(digit)?next.delete(digit):next.add(digit);return next});
function replaceCellNotes(r,c,nextSet){notes=notes.map((row,y)=>y===r?row.map((cell,x)=>x===c?nextSet:cell):row)}
const techniqueLessons={
  '显性唯一':'排除同行、同列和九宫内已经出现的数字；若候选只剩一个，就能确定该格。','隐性唯一':'观察同一行、列或九宫：如果某个数字只有一个候选位置，该位置就是答案。','区块排除':'若某数字在一个九宫内的候选位置全部落在同一行或列，可从该行或列的宫外格删除这个候选。','显性数对':'同一区域内若两个格子恰好拥有相同的两个候选，这两个数字被它们占据，可从其他格删除。','隐性数对':'同一区域内若两个数字都只出现在相同的两个格中，可删除这两格里的其他候选。','三数组':'三个格子的候选合集只有三个数字时，这三个数字被锁定，可从同一区域其他格删除。','X-Wing':'同一数字在两行中都只出现在相同两列，可从这两列的其他行删除该候选。','XY-Wing':'找到三个双候选格形成 XY、XZ、YZ 结构，可删除同时看见两个翼格的 Z 候选。','唯一矩形':'四格构成矩形且可能产生双解时，利用额外候选破坏矩形，避免无唯一解。','BUG+1':'所有未定格均为双值、仅一格为三值时，利用行列宫候选奇偶次数确定额外候选。','强弱链 / AIC':'沿候选的强链接和弱链接交替推导；链首尾形成矛盾或共同影响时即可排除候选。','ALS 组合':'寻找候选数比格子数多一个的近锁定集合，利用集合间受限公共候选进行排除。','多技巧链式推理':'先用区块、数组等局部排除缩小候选，再连接强弱关系完成链式排除。'
};
const lessonDetectorIds={'显性唯一':'nakedSingle','隐性唯一':'hiddenSingle','区块排除':'lockedCandidate','显性数对':'nakedPair','BUG+1':'bugPlusOne'};
const routeTechniqueIds={'显性唯一':'nakedSingle','隐性唯一':'hiddenSingle','区块排除':'lockedCandidate','显性数对':'nakedPair','隐性数对':'hiddenPair','三数组':'nakedTriple','X-Wing':'xWing','XY-Wing':'xyWing','唯一矩形':'uniqueRectangle','BUG+1':'bugPlusOne','强弱链 / AIC':'aic','ALS 组合':'als','多技巧链式推理':'aic'};
profile.soundEnabled=profile.soundEnabled!==false;profile.funRewards=[...(profile.funRewards||[])];

function loadProfile(){try{const stored=JSON.parse(localStorage.getItem('sudoku-profile-v1')||'{}'),data={name:'数独新手',avatar:'◈',avatarColor:'#6f8062',points:0,badges:[],techniqueCounts:{},techniqueUses:{},expressEnabled:true,rankIndex:0,playSeconds:[0,0,0,0,0],trialAttempts:{},trialWinStreaks:{},trialFastWins:{},bestTimes:{},highScores:{},featureRewards:[],gamesStarted:{},gamesCompleted:{},dailyFailures:{date:'',counts:{}},profileVersion:2,...stored};if(!stored.profileVersion){data.expressEnabled=true;data.profileVersion=2}data.rankIndex=Math.max(0,Math.min(4,data.rankIndex||0));data.playSeconds=[0,0,0,0,0].map((_,i)=>data.playSeconds?.[i]||0);data.trialAttempts={...(stored.trialAttempts||{})};data.trialWinStreaks={...(stored.trialWinStreaks||{})};data.trialFastWins={...(stored.trialFastWins||{})};data.bestTimes={...(stored.bestTimes||{})};data.highScores={...(stored.highScores||{})};data.gamesStarted={...(stored.gamesStarted||{})};data.gamesCompleted={...(stored.gamesCompleted||{})};data.dailyFailures={date:stored.dailyFailures?.date||'',counts:{...(stored.dailyFailures?.counts||{})}};for(const id of levelOrder)if(data.bestTimes[id]){data.gamesCompleted[id]=Math.max(1,data.gamesCompleted[id]||0);data.gamesStarted[id]=Math.max(data.gamesCompleted[id],data.gamesStarted[id]||0)}data.featureRewards=[...(stored.featureRewards||[])];data.techniqueCounts={...(stored.techniqueCounts||{})};data.techniqueUses={...(stored.techniqueUses||{})};for(const id of Object.keys(techniques))data.techniqueUses[id]=Math.max(data.techniqueUses[id]||0,data.techniqueCounts[id]||0);data.badges.forEach(id=>data.techniqueCounts[id]=Math.max(3,data.techniqueCounts[id]||0));return data}catch{return{name:'数独新手',avatar:'◈',avatarColor:'#6f8062',points:0,badges:[],techniqueCounts:{},techniqueUses:{},expressEnabled:true,rankIndex:0,trialWinStreaks:{},trialFastWins:{},dailyFailures:{date:'',counts:{}},profileVersion:2}}}
function rankIndexFromPoints(){let index=0;for(let i=0;i<ranks.length;i++)if(profile.points>=ranks[i].min)index=i;return index}
function displayPlayerName(){return lang==='en'&&profile.name==='数独新手'?'Sudoku Rookie':profile.name}
function applyLanguage(){
  document.documentElement.lang=lang==='en'?'en':'zh-CN';document.title=lang==='en'?'Sudoku Unbeaten':'数独求败';
  document.querySelector('#langButton').textContent=lang==='en'?'EN / 中':'中 / EN';
  const logoLetters=lang==='en'?['S','U','D','O']:['数','求','败','独'];document.querySelectorAll('[data-logo-part]').forEach(el=>el.textContent=logoLetters[+el.dataset.logoPart]||'');
  document.querySelector('#brandProfileButton').setAttribute('aria-label',lang==='en'?'Open player profile':'打开玩家档案');document.querySelector('#brandProfileButton').title=lang==='en'?'Player profile':'玩家档案';
  document.querySelector('.hint-symbol').textContent=lang==='en'?'AI':'思';
  document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=T(el.dataset.i18n));
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=T(el.dataset.i18nPlaceholder));
  document.querySelector('#customAvatarText').placeholder=T('customAvatarPlaceholder');
  document.querySelector('#customAvatarText').setAttribute('aria-label',lang==='en'?'Custom avatar text':'自定义头像文字');
  document.querySelector('#customAvatarColor').setAttribute('aria-label',lang==='en'?'Avatar color':'头像颜色');
  document.querySelector('#avatarPicker').setAttribute('aria-label',lang==='en'?'Choose avatar':'选择个人图案');
  document.querySelector('#closeProfile').setAttribute('aria-label',lang==='en'?'Close':'关闭');
  document.querySelectorAll('[data-i18n-level]').forEach(el=>el.textContent=levelLabel(el.dataset.i18nLevel));
  updateTechniqueRoute();renderProfile();updateJourney();updateSoundUnlock();if(solution.length)updatePad();if(!document.querySelector('#challengeNotice').hidden&&currentPassRate!==null)renderOpeningChallenge(currentPassRate);refreshCoachLanguage();if(!document.querySelector('#modal').hidden&&finished)showComplete();
}
function saveProfile(){const previousRank=profile.rankIndex;let passes=0,rewards=[],fresh;do{profile.rankIndex=rankIndexFromPoints();fresh=grantFeatureRewards();rewards.push(...fresh);passes++}while(fresh.length&&passes<5);profile.rankIndex=rankIndexFromPoints();if(profile.rankIndex<previousRank)profile.lastPlayedLevel=levelOrder[profile.rankIndex];localStorage.setItem('sudoku-profile-v1',JSON.stringify(profile));renderProfile();if(rewards.length&&document.querySelector('#joyMoment')){const total=rewards.reduce((sum,text)=>sum+(+(text.match(/\+(\d+)/)?.[1]||0)),0);setTimeout(()=>{if(total){flashScore(total);playCoinSound()}celebrateJoy('个人首次解锁',`${rewards.join(' · ')}，奖励已经到账。`,true)},120)}}
function renderProfile(){
  const rank=getRank(),rankIndex=profile.rankIndex,next=ranks[rankIndex+1],progress=next?Math.max(0,Math.min(100,Math.round((profile.points-rank.min)/(next.min-rank.min)*100))):100;
  const playerDisplayName=displayPlayerName();setAvatarDisplay(document.querySelector('#profileAvatar'),true);setAvatarDisplay(document.querySelector('#profileEmblem'));document.querySelector('#profileScore').textContent=profile.points;document.querySelector('#playerName').value=playerDisplayName;document.querySelector('#profileTitle').textContent=playerDisplayName;document.querySelector('#headerPlayerName').textContent=playerDisplayName;
  document.querySelector('#profileLevel').textContent=lang==='en'?levelLabel(levelOrder[rankIndex]):rank.name;document.querySelector('#profilePoints').textContent=profile.points;document.querySelector('#badgeCount').textContent=`${profile.badges.length}/${Object.keys(techniques).length}`;document.querySelector('#levelProgressText').textContent=next?(lang==='en'?`To ${levelLabel(levelOrder[rankIndex+1])}`:`距离「${next.name}」`):(lang==='en'?'Max rank':'已达最高等级');document.querySelector('#levelProgressValue').textContent=next?`${profile.points}/${next.min}`:'MAX';document.querySelector('#levelProgressBar').style.width=`${progress}%`;
  const correct=difficultyScore[level];document.querySelector('#scoreRuleText').textContent=lang==='en'?`Current ${levelLabel(level)} puzzle: correct +${correct}; wrong -${correct*2}. Special technique bonus is 2-10x the cell score.`:`当前${levelNames[level]}题目：正确 +${correct}；错误 -${correct*2}。特殊技巧奖励为单格分数的 2～10 倍。`;
  const trialTarget=ranks[rankIndex+1],trialWins=trialTarget?(profile.trialWinStreaks[trialTarget.name]||0):0,fastWins=trialTarget?(profile.trialFastWins[trialTarget.name]||0):0;document.querySelector('#rankTrialText').textContent=trialTarget?(lang==='en'?`Reach ${trialTarget.min} points to promote automatically; or challenge the next level: 3 clears in a row (${trialWins}/3), or 3 clears faster than average (${fastWins}/3).`:`达到 ${trialTarget.min} 分自动晋级；也可越级挑战。要求：在「${trialTarget.name}」连续 3 局通关（${trialWins}/3），或累计 3 局用时低于该级平均时间（${fastWins}/3）。`):(lang==='en'?'You are already at the highest rank.':'你已达到最高积分等级。');
  const totalStarted=levelOrder.reduce((sum,id)=>sum+(profile.gamesStarted[id]||0),0),totalCompleted=levelOrder.reduce((sum,id)=>sum+(profile.gamesCompleted[id]||0),0),totalRate=totalStarted?Math.round(totalCompleted/totalStarted*100):0;document.querySelector('#recordSummary').innerHTML=lang==='en'?`<span><b>${totalStarted}</b><small>Games</small></span><span><b>${totalCompleted}</b><small>Cleared</small></span><span><b>${totalRate}%</b><small>Clear rate</small></span>`:`<span><b>${totalStarted}</b><small>总局数</small></span><span><b>${totalCompleted}</b><small>完成局数</small></span><span><b>${totalRate}%</b><small>完成率</small></span>`;
  document.querySelector('#recordsGrid').innerHTML=levelOrder.map(id=>{const started=profile.gamesStarted[id]||0,completed=profile.gamesCompleted[id]||0,rate=started?Math.round(completed/started*100):0;return lang==='en'?`<div class="record-row"><strong>${levelLabel(id)}</strong><span>${started} games · ${rate}%</span><span>Best ${profile.bestTimes[id]?formatTime(profile.bestTimes[id]):'--:--'}</span><span>High ${profile.highScores[id]||0}</span></div>`:`<div class="record-row"><strong>${levelNames[id]}</strong><span>${started}盘 · ${rate}%</span><span>最佳 ${profile.bestTimes[id]?formatTime(profile.bestTimes[id]):'--:--'}</span><span>最高 ${profile.highScores[id]||0}</span></div>`}).join('');
  document.querySelector('#avatarPicker').innerHTML=avatars.slice(0,4).map(avatar=>`<button class="${profile.avatar===avatar?'active':''}" data-avatar="${avatar}" aria-label="${lang==='en'?'Choose avatar ':'选择图案'}${avatar}">${avatar}</button>`).join('');document.querySelector('#customAvatarColor').value=profile.avatarColor||'#6f8062';
  const gameLevelIndex=levelOrder.indexOf(level),expressAvailable=gameLevelIndex>=1,advancedExpress=gameLevelIndex>=2,toggle=document.querySelector('#expressToggle'),toggleRow=document.querySelector('#expressToggleRow');toggle.checked=expressAvailable&&profile.expressEnabled;toggle.disabled=!expressAvailable;toggleRow.classList.toggle('locked',!expressAvailable);document.querySelector('#expressStatus').textContent=lang==='en'?(advancedExpress?'Current puzzle: advanced express fill':expressAvailable?'Current puzzle: basic express fill unlocked':'Unavailable for this level'):(advancedExpress?'当前局：高级快速填充':expressAvailable?'当前局：基础快速填充已解锁':'当前局不可使用');document.querySelector('#expressHelp').textContent=lang==='en'?(advancedExpress?'Supports last empty cell in box/row/column, last digit reminder, and final 9-cell fill.':expressAvailable?'Tap to fill when a row, column, or box has only one empty cell left.':'Beginner puzzles cannot use express fill.'):(advancedExpress?'支持九宫、行、列、数字末格提醒及最后 9 格填充。':expressAvailable?'支持行、列或九宫只剩最后一个空格时点击填入。':'初级局不能使用快速填充。');
  const notesButton=document.querySelector('#notesButton'),eraseButton=document.querySelector('#eraseButton'),autoNotesButton=document.querySelector('#autoNotesButton'),autoNotesLocked=gameLevelIndex<2;notesButton.disabled=false;eraseButton.disabled=false;autoNotesButton.disabled=autoNotesLocked;notesButton.title='连续候选标记';eraseButton.title='擦除数字或候选标记';autoNotesButton.title=autoNotesLocked?'高级局解锁一键标记':`一键标记所有空格，扣 ${autoNotesCost[level]} 分`;updateActiveNoteNumber()
  document.querySelector('#badgeGrid').innerHTML=Object.entries(techniques).map(([id,t])=>{const earned=profile.badges.includes(id),count=Math.min(3,profile.techniqueCounts[id]||0),uses=profile.techniqueUses[id]||0;return`<button type="button" class="badge ${earned?'earned':'locked'}" data-technique="${id}" title="${lang==='en'?'View details for':'点击查看'}${techniqueName(id)}"><i>${earned?t.icon:count||'?'}</i><strong>${techniqueName(id)}</strong><small>${earned?(lang==='en'?`Collected · ${uses} uses`:`已收藏 · ${uses}次`):(lang==='en'?`${count}/3 · ${uses} uses`:`${count}/3 · 使用${uses}次`)}</small></button>`}).join('')
  updateDifficultyAccess();
}
function setAvatarDisplay(element,small=false){element.innerHTML='';if(typeof profile.avatar==='string'&&profile.avatar.startsWith('data:image/')){const img=document.createElement('img');img.src=profile.avatar;img.alt='玩家头像';element.append(img);element.style.backgroundColor='transparent'}else{element.textContent=profile.avatar||'◈';element.style.color=profile.avatarColor||'var(--accent)';if(!small)element.style.backgroundColor=`color-mix(in srgb, ${profile.avatarColor||'var(--accent)'} 16%, transparent)`}}
function getRank(){return ranks[profile.rankIndex]||ranks[0]}
function getScoringRank(){return ranks[Math.max(0,levelOrder.indexOf(level))]}
function formatDuration(total){const minutes=Math.floor(total/60);return minutes<60?`${minutes}分钟`:`${Math.floor(minutes/60)}小时${minutes%60?`${minutes%60}分`:''}`}
function trialEligibility(targetIndex){if(targetIndex<=profile.rankIndex)return{eligible:true,reason:'已解锁'};if(targetIndex>profile.rankIndex+1)return{eligible:false,reason:`请先完成${ranks[profile.rankIndex+1].name}挑战`};const target=ranks[targetIndex],wins=profile.trialWinStreaks[target.name]||0,fast=profile.trialFastWins[target.name]||0;return{eligible:true,reason:`越级挑战：连续通关 ${wins}/3 · 快于平均累计 ${fast}/3`}}
function updateDifficultyAccess(){document.querySelectorAll('.difficulty button').forEach(btn=>{const i=levelOrder.indexOf(btn.dataset.level),trial=i===profile.rankIndex+1,status=trialEligibility(i),accessible=status.eligible;btn.classList.toggle('locked',!accessible);btn.classList.toggle('lower',i<profile.rankIndex);btn.classList.toggle('trial',trial&&accessible);btn.title=accessible?(trial?status.reason:i<profile.rankIndex?'已解锁，按较低等级积分计算':'当前等级'):status.reason})}
function selectDefaultLevel(){const saved=profile.lastPlayedLevel,savedIndex=levelOrder.indexOf(saved);level=saved&&savedIndex>=0&&trialEligibility(savedIndex).eligible?saved:levelOrder[profile.rankIndex];document.querySelectorAll('.difficulty button').forEach(button=>button.classList.toggle('active',button.dataset.level===level))}
function changePoints(amount,{celebrate=true}={}){profile.points=Math.max(0,profile.points+amount);saveProfile();if(amount){flyScore(amount);playSwooshSound(amount)}if(amount>0){flashScore(amount);playCoinSound();if(celebrate)playJoyMelody()}return amount>0?`+${amount}`:`${amount}`}
function updateContinueButton(){const button=document.querySelector('#continueWithPoints');if(!button)return;const cost=continueCost[level],canContinue=profile.points>=cost;button.disabled=!canContinue;button.textContent=canContinue?(lang==='en'?`Continue for ${cost} points`:`扣 ${cost} 积分继续`):(lang==='en'?`Not enough points (need ${cost})`:`积分不足（需要 ${cost}）`)}
function applyRechargeProduct(){
  profile.points=Math.max(0,profile.points+rechargeProduct.points);
  localStorage.setItem('sudoku-profile-v1',JSON.stringify(profile));
  renderProfile();updateContinueButton();flashScore(rechargeProduct.points);playCoinSound();playJoyMelody();
  const message=lang==='en'?`Credited: ${rechargeProduct.enPrice} = ${rechargeProduct.points} points`:`已到账：${rechargeProduct.zhPrice} = ${rechargeProduct.points} 点`;
  const failPenalty=document.querySelector('#failPenalty');if(failPenalty&&!document.querySelector('#failModal').hidden)failPenalty.textContent=`${message} · ${lang==='en'?'Current points':'当前积分'} ${profile.points}`;
  const streakText=document.querySelector('#streakFailText');if(streakText&&!document.querySelector('#streakFailModal').hidden)streakText.textContent=`${message} · ${lang==='en'?'You can keep this rank now.':'现在可以保留当前等级。'}`;
  showToast(message);
}
window.sudokuRecharge=applyRechargeProduct;
document.addEventListener('click',e=>{const button=e.target.closest?.('#rechargeContinue,#rechargeKeepRank');if(!button)return;e.preventDefault();e.stopPropagation();applyRechargeProduct()},true);
function flashScore(amount){const score=document.querySelector('#profileScore');if(!score)return;score.dataset.gain=`+${amount}`;score.classList.remove('score-gain');void score.offsetWidth;score.classList.add('score-gain');setTimeout(()=>score.classList.remove('score-gain'),900)}
function flyScore(amount){const board=document.querySelector('#board'),target=document.querySelector('#profileScore');if(!board||!target)return;const from=board.getBoundingClientRect(),to=target.getBoundingClientRect(),chip=document.createElement('b');chip.className=`score-fly ${amount<0?'minus':'plus'}`;chip.textContent=`${amount>0?'+':''}${amount}`;chip.style.left=`${from.left+from.width/2}px`;chip.style.top=`${from.top+from.height/2}px`;chip.style.setProperty('--tx',`${to.left+to.width/2-(from.left+from.width/2)}px`);chip.style.setProperty('--ty',`${to.top+to.height/2-(from.top+from.height/2)}px`);document.body.append(chip);setTimeout(()=>chip.remove(),900)}
let soundCtx=null,soundUnlocked=false;
function getSoundContext(){const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return null;if(!soundCtx||soundCtx.state==='closed')soundCtx=new AudioCtx();return soundCtx}
function updateSoundUnlock(){const button=document.querySelector('#soundUnlock');if(!button)return;button.textContent=lang==='en'?'Enable sound':'开启音效';button.setAttribute('aria-label',lang==='en'?'Enable game sound':'开启游戏音效');button.hidden=profile.soundEnabled&&soundUnlocked}
function playPrimeTone(ctx){const now=ctx.currentTime;[523.25,659.25,783.99].forEach((frequency,i)=>{const oscillator=ctx.createOscillator(),gain=ctx.createGain(),start=now+i*.075;oscillator.type=i%2?'triangle':'sine';oscillator.frequency.setValueAtTime(frequency,start);gain.gain.setValueAtTime(.001,start);gain.gain.exponentialRampToValueAtTime(.085,start+.012);gain.gain.exponentialRampToValueAtTime(.001,start+.16);oscillator.connect(gain).connect(ctx.destination);oscillator.start(start);oscillator.stop(start+.18)})}
function markSoundUnlocked(){soundUnlocked=true;updateSoundUnlock();updateSoundButton?.()}
function primeAudio(){profile.soundEnabled=true;localStorage.setItem('sudoku-profile-v1',JSON.stringify(profile));try{const ctx=getSoundContext();if(!ctx){showToast(lang==='en'?'This browser does not support game sound':'这个浏览器暂不支持游戏音效');return}const play=()=>{playPrimeTone(ctx);markSoundUnlocked();showToast(lang==='en'?'Sound enabled':'音效已开启')};if(ctx.state==='suspended')ctx.resume().then(play).catch(()=>showToast(lang==='en'?'Tap again to enable sound':'请再点一次开启音效'));else play()}catch{showToast(lang==='en'?'Tap again to enable sound':'请再点一次开启音效')}}
function unlockAudio(){if(!profile.soundEnabled)return;try{const ctx=getSoundContext();if(!ctx)return;if(ctx.state==='suspended')ctx.resume().then(markSoundUnlocked).catch(()=>{});else markSoundUnlocked()}catch{}}
['pointerdown','touchstart','keydown'].forEach(type=>document.addEventListener(type,unlockAudio,{capture:true,passive:true}));
function withSoundContext(run){if(!profile.soundEnabled)return;try{const ctx=getSoundContext();if(!ctx)return;if(ctx.state==='suspended')ctx.resume().then(()=>run(ctx)).catch(()=>{});else run(ctx)}catch{}}
function playTone(frequency,{delay=0,duration=.16,type='sine',volume=.07,slideTo=null}={}){withSoundContext(ctx=>{const oscillator=ctx.createOscillator(),gain=ctx.createGain(),start=ctx.currentTime+delay;oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,start);if(slideTo)oscillator.frequency.exponentialRampToValueAtTime(slideTo,start+duration*.88);gain.gain.setValueAtTime(.001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.012);gain.gain.exponentialRampToValueAtTime(.001,start+duration);oscillator.connect(gain).connect(ctx.destination);oscillator.start(start);oscillator.stop(start+duration+.02)})}
function playNumberTone(n){const scale=[261.63,293.66,329.63,349.23,392,440,493.88,523.25,587.33];playTone(scale[n-1]||523.25,{duration:.15,type:'sine',volume:.075})}
function playCorrectSound(){[659.25,783.99,1046.5].forEach((f,i)=>playTone(f,{delay:i*.045,duration:.14,type:'triangle',volume:.065}))}
function playWrongSound(){playTone(196,{duration:.25,type:'sawtooth',volume:.055,slideTo:146.83});setTimeout(()=>playTone(130.81,{duration:.15,type:'triangle',volume:.05}),80)}
function playEraseSound(){[392,329.63,261.63].forEach((f,i)=>playTone(f,{delay:i*.035,duration:.1,type:'triangle',volume:.045}))}
function playHintSound(){[523.25,659.25,587.33].forEach((f,i)=>playTone(f,{delay:i*.055,duration:.13,type:'sine',volume:.06}))}
function playAutoNotesSound(){[392,493.88,587.33,783.99].forEach((f,i)=>playTone(f,{delay:i*.04,duration:.11,type:'triangle',volume:.055}))}
function playSwooshSound(amount=1){const up=amount>=0;playTone(up?740:330,{duration:.16,type:'triangle',volume:.035,slideTo:up?1480:165});setTimeout(()=>playTone(up?1174.66:220,{duration:.1,type:'sine',volume:.025}),65)}
function playFailMusic(){[392,330,294,349,262,392].forEach((f,i)=>playTone(f,{delay:i*.105,duration:i===5?.18:.11,type:i%2?'square':'triangle',volume:.045,slideTo:i===2?330:null}))}
function playVictoryMusic(){[523.25,659.25,783.99,1046.5,987.77,1046.5,1318.51].forEach((f,i)=>playTone(f,{delay:i*.085,duration:i>4?.22:.13,type:i===6?'triangle':'sine',volume:i===6?.075:.06}));setTimeout(()=>playApplause(),390)}
function playFinalRunMusic(){const notes=[523.25,659.25,783.99,1046.5,783.99,987.77,1174.66,1318.51,1567.98,1318.51,1567.98,1760];notes.forEach((f,i)=>playTone(f,{delay:i*.12,duration:i>8?.22:.13,type:i%3===0?'triangle':'sine',volume:i>8?.07:.052}));setTimeout(()=>playApplause(),980)}
function playCoinSound(){withSoundContext(ctx=>{const now=ctx.currentTime;[880,1320].forEach((frequency,i)=>{const oscillator=ctx.createOscillator(),gain=ctx.createGain(),start=now+i*.065;oscillator.type='triangle';oscillator.frequency.setValueAtTime(frequency,start);gain.gain.setValueAtTime(.001,start);gain.gain.exponentialRampToValueAtTime(.11,start+.012);gain.gain.exponentialRampToValueAtTime(.001,start+.13);oscillator.connect(gain).connect(ctx.destination);oscillator.start(start);oscillator.stop(start+.15)})})}
function unlockTechnique(id){
  const t=techniques[id];if(!t)return;profile.techniqueUses[id]=(profile.techniqueUses[id]||0)+1;if(profile.badges.includes(id)){saveProfile();return}const previous=profile.techniqueCounts[id]||0,count=Math.min(3,previous+1);profile.techniqueCounts[id]=count;if(previous===0){profile.points+=100;gameScore+=100;flashScore(100);playCoinSound()}saveProfile();pendingBadge=count===3?id:null;
  const stages=['','个人首次解锁 · 1/3','技巧练习 · 2/3','技巧掌握 · 3/3'];document.querySelector('#rewardStage').textContent=stages[count];document.querySelector('#rewardIcon').textContent=t.icon;document.querySelector('#rewardTitle').textContent=t.name;if(previous===0){playJoyMelody();celebrateJoy('新技巧已点亮',`「${t.name}」进入你的学习档案 · +100 智慧点`,false)}
  document.querySelector('#rewardDesc').textContent=count===3?`${t.desc} 你已连续识别 3 次，现在可以收藏这枚勋章。`:count===2?`${t.desc} 再成功识别 1 次即可收藏勋章。`:t.desc;
  document.querySelector('#rewardPoints').textContent=count===1?'+100 智慧点':count===3?'已达到勋章收藏条件':'本次不重复奖励积分';document.querySelector('#claimReward').textContent=count===3?'收藏勋章':'继续练习';document.querySelector('#rewardModal').hidden=false
}
function showTechniqueDetails(id){const t=techniques[id];if(!t)return;const uses=profile.techniqueUses[id]||0,mastery=Math.min(3,profile.techniqueCounts[id]||0),earned=profile.badges.includes(id);document.querySelector('#techniqueDetailIcon').textContent=earned?t.icon:'?';document.querySelector('#techniqueDetailName').textContent=techniqueName(id);document.querySelector('#techniqueDetailDesc').textContent=techniqueDesc(id);document.querySelector('#techniqueUseCount').textContent=uses;document.querySelector('#techniqueMastery').textContent=`${mastery}/3`;document.querySelector('#techniqueBadgeStatus').textContent=lang==='en'?(earned?'Badge collected':mastery>=3?'Ready to collect badge':`${3-mastery} more uses to collect`):(earned?'勋章已收藏':mastery>=3?'等待收藏勋章':`再使用 ${3-mastery} 次可收藏`);document.querySelector('#techniqueModal').hidden=false}

function shuffled(arr){return [...arr].sort(()=>Math.random()-.5)}
function pattern(r,c){return(r*3+Math.floor(r/3)+c)%9}
function makeSolution(){
  const rows=shuffled([0,1,2]).flatMap(b=>shuffled([0,1,2]).map(r=>b*3+r));
  const cols=shuffled([0,1,2]).flatMap(b=>shuffled([0,1,2]).map(c=>b*3+c));
  const nums=shuffled([1,2,3,4,5,6,7,8,9]);
  return rows.map(r=>cols.map(c=>nums[pattern(r,c)]));
}
function gridFromString(text){return Array.from({length:9},(_,r)=>[...text.slice(r*9,r*9+9)].map(Number))}
function solveOne(grid){let target=null,best=null;for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(!grid[r][c]){const opts=[];for(let n=1;n<=9;n++)if(valid(grid,r,c,n))opts.push(n);if(!opts.length)return false;if(!best||opts.length<best.length){target={r,c};best=opts}}if(!target)return true;for(const n of best){grid[target.r][target.c]=n;if(solveOne(grid))return true;grid[target.r][target.c]=0}return false}
function transformedExpertPuzzle(text){
  const source=gridFromString(text),rows=shuffled([0,1,2]).flatMap(b=>shuffled([0,1,2]).map(r=>b*3+r)),cols=shuffled([0,1,2]).flatMap(b=>shuffled([0,1,2]).map(c=>b*3+c)),digits=shuffled([1,2,3,4,5,6,7,8,9]),grid=rows.map(r=>cols.map(c=>source[r][c]?digits[source[r][c]-1]:0));solution=grid.map(row=>[...row]);solveOne(solution);return grid;
}
function countSolutions(grid,limit=2){
  let count=0;
  function solve(){
    let br=-1,bc=-1,opts=null;
    for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(!grid[r][c]){
      const possible=[];for(let n=1;n<=9;n++)if(valid(grid,r,c,n))possible.push(n);
      if(!possible.length)return;if(!opts||possible.length<opts.length){br=r;bc=c;opts=possible}
    }
    if(br<0){count++;return}
    for(const n of opts){grid[br][bc]=n;solve();grid[br][bc]=0;if(count>=limit)return}
  }solve();return count;
}
function valid(grid,r,c,n){for(let i=0;i<9;i++)if(grid[r][i]===n||grid[i][c]===n)return false;let rr=Math.floor(r/3)*3,cc=Math.floor(c/3)*3;for(let y=rr;y<rr+3;y++)for(let x=cc;x<cc+3;x++)if(grid[y][x]===n)return false;return true}
function makePuzzle(){
  const templates=skillTemplates[level],template=templates[Math.floor(Math.random()*templates.length)];return transformedExpertPuzzle(template);
}
function newGame(){
  profile.lastPlayedLevel=level;
  clearInterval(timerId);const levelIndex=levelOrder.indexOf(level);currentGameIsTrial=levelIndex===profile.rankIndex+1;profile.gamesStarted[level]=(profile.gamesStarted[level]||0)+1;saveProfile();finished=false;expressFinishing=false;completionAwarded=false;completionRecord=null;scoredCells=new Set();gameTechniques=new Set();rewardedGameTechniques=new Set();gameScore=0;mistakes=0;hints=3;seconds=0;selected=null;selectedPadNumber=null;selectedRouteTechnique=null;lastCoachContext=null;currentPassRate=null;noteMode=false;activeNoteNumber=null;noteInputMode=null;correctStreak=0;journeyMoments=new Set();document.querySelector('#notesButton').classList.remove('active');document.querySelector('#notesButton').setAttribute('aria-pressed','false');updateActiveNoteNumber();puzzle=makePuzzle();values=puzzle.map(r=>[...r]);initialEmptyCount=values.flat().filter(v=>!v).length;notes=Array.from({length:9},()=>Array.from({length:9},()=>new Set()));
  mistakesEl.textContent='0/3';document.querySelector('#hintCount').textContent=hints;document.querySelector('#learningHint').hidden=true;timerEl.textContent='00:00';updateTechniqueRoute();render();updateJourney();showOpeningChallenge();timerId=setInterval(tick,1000);
}
function renderOpeningChallenge(rate){const notice=document.querySelector('#challengeNotice');notice.innerHTML=lang==='en'?`<span>${T('challenge')}</span><strong>${T('passRate')} <b>${rate}%</b></strong><small>${rate<=12?'A true expert puzzle. Can you be among the few who clear it?':rate<=25?'This one stops most players. Keep your rhythm steady.':'Focus and observe; you can outperform most players.'}</small>`:`<span>本局挑战</span><strong>参考通关率仅 <b>${rate}%</b></strong><small>${rate<=12?'真正的高手局，看看你能否成为少数通关者。':rate<=25?'这局会拦住大多数玩家，稳住节奏。':'专注观察，你有机会超过大多数玩家。'}</small>`;notice.hidden=false;notice.classList.remove('closing');notice.classList.add('show')}
function showOpeningChallenge(){const [min,max]=passRateRanges[level];currentPassRate=Math.floor(Math.random()*(max-min+1))+min;renderOpeningChallenge(currentPassRate)}
function updateJourney(){const solved=values.length?values.flat().filter((n,i)=>n===solution.flat()[i]).length-puzzle.flat().filter(Boolean).length:0,progress=initialEmptyCount?Math.max(0,Math.round(solved/initialEmptyCount*100)):0;document.querySelector('#journeyBar').style.width=`${progress}%`;document.querySelector('#comboText').textContent=lang==='en'?`Streak ${correctStreak}`:`连对 ${correctStreak}`;document.querySelector('#journeyText').textContent=lang==='en'?(progress>=90?'Final stretch. Steady finish.':progress>=50?'Halfway through; the pattern is opening up.':correctStreak>=5?'You have the rhythm. Keep it.':'Slow down. Every step counts.'):(progress>=90?'最后一小段，稳稳收官':progress>=50?'已经走过一半，思路正在打开':correctStreak>=5?'手感来了，保持这个节奏':'慢慢来，每一步都算数');if(progress>=50&&!journeyMoments.has('half')){journeyMoments.add('half');celebrateJoy(lang==='en'?'Halfway there':'棋盘过半',lang==='en'?'You have solved half the board. Breathe, then continue.':'你已经解开一半，先呼吸一下，再继续。',false)}}
function rewardRhythm(){correctStreak++;updateJourney();const rewards={5:5,10:10,20:20},bonus=rewards[correctStreak];if(bonus&&!journeyMoments.has(`streak${correctStreak}`)){journeyMoments.add(`streak${correctStreak}`);changePoints(bonus);gameScore+=bonus;celebrateJoy(lang==='en'?`${correctStreak} correct in a row!`:`连续答对 ${correctStreak} 格`,lang==='en'?`Streak bonus +${bonus} points`:`专注节奏奖励 +${bonus} 智慧点`,true)}}
function celebrateJoy(title,text,music=true){const el=document.querySelector('#joyMoment');document.querySelector('#joyTitle').textContent=title;document.querySelector('#joyText').textContent=text;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');if(music)playJoyMelody();setTimeout(()=>el.classList.remove('show'),2700)}
function playJoyMelody(){withSoundContext(ctx=>{const notes=[523.25,659.25,783.99,1046.5];notes.forEach((frequency,i)=>{const oscillator=ctx.createOscillator(),gain=ctx.createGain(),start=ctx.currentTime+i*.11;oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.001,start);gain.gain.exponentialRampToValueAtTime(.09,start+.018);gain.gain.exponentialRampToValueAtTime(.001,start+.2);oscillator.connect(gain).connect(ctx.destination);oscillator.start(start);oscillator.stop(start+.22)})})}
function updateTechniqueRoute(){const route=advancedRoutes[level],box=document.querySelector('#techniqueRoute');box.hidden=!route;if(route)document.querySelector('#techniqueRouteText').innerHTML=route.map(name=>`<button type="button" data-route-technique="${name}" class="${selectedRouteTechnique===name?'active':''}">${routeLabel(name)}</button>`).join('')}
function render(){
  boardEl.innerHTML='';for(let r=0;r<9;r++)for(let c=0;c<9;c++){
    const cell=document.createElement('button');cell.className='cell';cell.dataset.r=r;cell.dataset.c=c;cell.setAttribute('role','gridcell');cell.setAttribute('aria-label',`第${r+1}行第${c+1}列${values[r][c]||'空'}`);
    if(puzzle[r][c])cell.classList.add('given');else if(values[r][c])cell.classList.add('user');setCellContent(cell,r,c);cell.addEventListener('click',()=>select(r,c));boardEl.append(cell);
  }updateHighlights();updatePad();
}
function select(r,c){
  if(finished||expressFinishing)return;document.querySelectorAll('.cell.coached').forEach(cell=>cell.classList.remove('coached'));selected={r,c};updateHighlights();const gameLevelIndex=levelOrder.indexOf(level);if(noteMode){if(noteInputMode==='number'&&activeNoteNumber){addContinuousNote(activeNoteNumber);return}noteInputMode='cell';activeNoteNumber=null;updateActiveNoteNumber();if(!values[r][c])showToast(lang==='en'?'Cell note mode: choose multiple candidates':'当前为空格标记模式：可连续选择多个候选数字');return}if(gameLevelIndex<1||!profile.expressEnabled||values[r][c])return;
  const n=solution[r][c],rowEmpty=values[r].filter(value=>!value).length,colEmpty=values.filter(row=>!row[c]).length,boxRow=Math.floor(r/3)*3,boxCol=Math.floor(c/3)*3,boxEmpty=values.slice(boxRow,boxRow+3).flatMap(row=>row.slice(boxCol,boxCol+3)).filter(value=>!value).length,numberRemaining=9-values.flat().filter(value=>value===n).length;
  const reason=boxEmpty===1?(lang==='en'?'last empty cell in this box':'本九宫最后一个空格'):rowEmpty===1?(lang==='en'?'last empty cell in this row':'本行最后一个空格'):colEmpty===1?(lang==='en'?'last empty cell in this column':'本列最后一个空格'):gameLevelIndex>=2&&numberRemaining===1?(lang==='en'?`last position for ${n}`:`数字 ${n} 的最后一格`):null;
  if(reason){values[r][c]=n;const cell=getCell(r,c);cell.textContent=n;cell.classList.add('user','express');removePeerNotes(r,c,n);const key=`${r}-${c}`;if(!scoredCells.has(key)){scoredCells.add(key);const gained=difficultyScore[level];changePoints(gained);gameScore+=gained;rewardRhythm()}updatePad();if(!finishLastNine()){showToast(lang==='en'?`Express fill: ${reason} · +${difficultyScore[level]} points`:`快速填充：${reason} · +${difficultyScore[level]} 分`);checkComplete()}}
}
function finishLastNine(){
  if(levelOrder.indexOf(level)<2||!profile.expressEnabled||finished||expressFinishing)return false;const empty=[];for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(!values[r][c])empty.push({r,c});if(empty.length!==9)return false;
  expressFinishing=true;lastFinalRunAt=Date.now();clearInterval(timerId);playFinalRunMusic();showToast(lang==='en'?'Express fill: filling the final 9 cells…':'快速填充：正在完成最后 9 格…');empty.forEach(({r,c},index)=>setTimeout(()=>{values[r][c]=solution[r][c];notes[r][c].clear();const cell=getCell(r,c);cell.textContent=solution[r][c];cell.classList.add('user','express');removePeerNotes(r,c,solution[r][c]);updatePad();updateHighlights();if(index===empty.length-1)setTimeout(()=>{showToast(lang==='en'?'Final 9 cells filled':'最后 9 格填充完成');setTimeout(()=>{expressFinishing=false;checkComplete()},850)},350)},index*190));return true;
}
function updateHighlights(){
  document.querySelectorAll('.cell').forEach(el=>{const r=+el.dataset.r,c=+el.dataset.c;el.classList.remove('selected','related','same');if(!selected)return;if(r===selected.r&&c===selected.c)el.classList.add('selected');else if(r===selected.r||c===selected.c||(Math.floor(r/3)===Math.floor(selected.r/3)&&Math.floor(c/3)===Math.floor(selected.c/3)))el.classList.add('related');if(values[selected.r][selected.c]&&values[r][c]===values[selected.r][selected.c])el.classList.add('same')})
  updateSelectedPadNumber();
}
function setCellContent(cell,r,c){if(values[r][c]){cell.textContent=values[r][c];return}const marks=notes[r]?.[c]||new Set();cell.innerHTML=`<span class="cell-notes">${[1,2,3,4,5,6,7,8,9].map(n=>marks.has(n)?`<i data-note="${n}" class="${selectedPadNumber===n?'note-focus':''}">${n}</i>`:'<i></i>').join('')}</span>`}
function noteConflicts(r,c,n){if(values[r].includes(n)||values.some(row=>row[c]===n))return true;const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let y=br;y<br+3;y++)for(let x=bc;x<bc+3;x++)if(values[y][x]===n)return true;return false}
function nakedTriplePatterns(){
  const units=[];for(let i=0;i<9;i++){units.push([...Array(9)].map((_,c)=>({r:i,c})));units.push([...Array(9)].map((_,r)=>({r,c:i})));units.push([...Array(9)].map((_,k)=>({r:Math.floor(i/3)*3+Math.floor(k/3),c:(i%3)*3+k%3})))}
  const patterns=[];
  for(const unit of units){
    const cells=unit.filter(p=>!values[p.r][p.c]&&candidatesAt(p.r,p.c).length>=2&&candidatesAt(p.r,p.c).length<=3);
    for(let a=0;a<cells.length-2;a++)for(let b=a+1;b<cells.length-1;b++)for(let c=b+1;c<cells.length;c++){
      const triple=[cells[a],cells[b],cells[c]],digits=[...new Set(triple.flatMap(p=>candidatesAt(p.r,p.c)))];if(digits.length!==3)continue;
      const victims=unit.filter(p=>!values[p.r][p.c]&&!triple.some(t=>t.r===p.r&&t.c===p.c)).map(p=>({r:p.r,c:p.c,removed:candidatesAt(p.r,p.c).filter(n=>digits.includes(n))})).filter(p=>p.removed.length);
      if(victims.length)patterns.push({cells:triple,digits,victims});
    }
  }
  return patterns;
}
function tripleForElimination(r,c,n){return nakedTriplePatterns().find(pattern=>pattern.victims.some(v=>v.r===r&&v.c===c&&v.removed.includes(n)))||null}
function tripleForPlacement(r,c,n){return nakedTriplePatterns().find(pattern=>{const victim=pattern.victims.find(v=>v.r===r&&v.c===c);if(!victim)return false;const remaining=candidatesAt(r,c).filter(x=>!pattern.digits.includes(x));return remaining.length===1&&remaining[0]===n})||null}
function openCoachContext(context){lastCoachContext=context;const panel=document.querySelector('#coachPanel'),log=document.querySelector('#coachLog');if(panel)panel.hidden=false;if(log)log.innerHTML=''}
function setCoachHint(title,reason,context={}){document.querySelector('#hintTitle').textContent=title;document.querySelector('#hintReason').textContent=reason;document.querySelector('#learningHint').hidden=false;openCoachContext({title,reason,...context})}
function refreshCoachLanguage(){const card=document.querySelector('#learningHint');if(!card||card.hidden||!lastCoachContext||!Number.isInteger(lastCoachContext.r)||!Number.isInteger(lastCoachContext.c))return;const {r,c,n,technique}=lastCoachContext;if(n)showMoveFeedback(r,c,n,technique||detectTechnique(r,c,n),technique==='nakedSingle'?explainNakedSingle(r,c,n):null);else showLearningHint(r,c)}
function cellLabel(r,c){return lang==='en'?`row ${r+1}, column ${c+1}`:`第 ${r+1} 行第 ${c+1} 列`}
function shortCellLabel(r,c){return lang==='en'?`R${r+1}C${c+1}`:`第${r+1}行第${c+1}列`}
function numList(list){return list&&list.length?list.join(lang==='en'?', ':'、'):(lang==='en'?'none':'无')}
function coachNameFromTitle(title=''){const hit=Object.entries(techniques).find(([id,t])=>title.includes(t.name)||title.includes(techniqueName(id)));return hit?techniqueName(hit[0]):title.split('·').pop()?.trim()||(lang==='en'?'this step':'当前这一步')}
function selectedCandidateText(){if(!selected)return lang==='en'?'No cell is selected yet.':'还没有选中格子';const opts=candidatesAt(selected.r,selected.c);return opts.length?(lang==='en'?`${cellLabel(selected.r,selected.c)} candidates: ${numList(opts)}`:`${cellLabel(selected.r,selected.c)}候选是 ${numList(opts)}`):(lang==='en'?`${cellLabel(selected.r,selected.c)} has no pending candidates.`:`${cellLabel(selected.r,selected.c)}现在没有待排候选`)}
function findCoachNextTarget(){const empty=[];for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(!values[r][c])empty.push({r,c,opts:candidatesAt(r,c)});return empty.sort((a,b)=>a.opts.length-b.opts.length)[0]}
function coachReply(kind,text=''){const ctx=lastCoachContext||(lang==='en'?{title:'AI coach',reason:'Select a cell or tap Hint, and I will explain from the current board.'}:{title:'思考教练',reason:'先选中一个格子，或点击提示，我再结合当前棋盘解释。'}),name=coachNameFromTitle(ctx.title),target=findCoachNextTarget();let reply='';
  if(lang==='en'){
    if(kind==='why'||/why|explain|reason|understand/i.test(text))reply=`My reasoning is: ${ctx.reason} If that feels too fast, start with the highlighted cell, then check its row, column, and 3×3 box one by one.`;
    else if(kind==='disagree'||/wrong|disagree|not|doubt/i.test(text))reply=`Good challenge. Treat it as a claim to verify, not a command: ${selectedCandidateText()} Check three things: row conflict, column conflict, and whether the same digit still has another valid place in the box.`;
    else if(kind==='simpler'||/simple|opening|stuck|break/i.test(text))reply=target?`A steadier opening is usually the cell with the fewest candidates. I would inspect ${cellLabel(target.r,target.c)} first. Candidates: ${numList(target.opts)}. If it is not single, check whether any of those digits has only one place in the row, column, or box.`:'There are no empty cells left; check for mistakes or wait for completion.';
    else if(kind==='next'||/next|where|what/i.test(text))reply=target?`Next, look at ${cellLabel(target.r,target.c)}. Candidates: ${numList(target.opts)}. Do not guess yet; first look for a “single position” in the same row, column, or box.`:'There is no remaining empty cell to analyze.';
    else reply=`I will read your question through “${name}”. Current explanation: ${ctx.reason} If you want to challenge it, point out which candidate may still fit elsewhere.`;
  }else if(kind==='why'||/为什么|看不懂|解释|原因/.test(text))reply=`我的判断依据是：${ctx.reason} 如果你觉得跳得太快，先只看被加粗边框标出的格子，再看它所在的行、列、九宫，逐个排除候选。`;
  else if(kind==='disagree'||/不对|错|瞎说|不是|质疑/.test(text))reply=`可以质疑，这正是好习惯。我们先不把它当答案，只当一个待验证推断：${selectedCandidateText()}。你可以检查三处：同行是否已有冲突、同列是否已有冲突、九宫内是否还有同数字可落点。若任一处对不上，就说明这条解析需要改进。`;
  else if(kind==='simpler'||/简单|突破|卡住|入口/.test(text))reply=target?`更稳的下手点通常是候选最少的格子。当前我建议先看${cellLabel(target.r,target.c)}，候选为 ${numList(target.opts)}。如果它不是唯一，再看这些数字在同行、同列、九宫里是否只有一个落点。`:'这盘已经没有空格了，可以检查是否有错误或等待完成检测。';
  else if(kind==='next'||/下一步|看哪里|怎么办/.test(text))reply=target?`下一步先看${cellLabel(target.r,target.c)}。它的候选是 ${numList(target.opts)}。我的建议是：先不要猜，先观察这些候选数字在同一行、同一列、同一宫里有没有“唯一位置”。`:'当前没有可继续分析的空格。';
  else reply=`我先按「${name}」来理解你的问题。当前解析是：${ctx.reason} 如果你要反驳它，最好指出“哪个候选其实还可以放在别处”，我就能顺着这个点继续拆。`;
  const log=document.querySelector('#coachLog');if(log){const fallback=lang==='en'?{why:'Why?',disagree:'I disagree',simpler:'Any simpler opening?',next:'Where next?'}:{why:'为什么？',disagree:'我觉得不对',simpler:'有没有更简单的突破口？',next:'下一步看哪里？'};log.insertAdjacentHTML('beforeend',`<div class="coach-msg user">${text||(fallback[kind]||(lang==='en'?'Follow-up':'追问'))}</div><div class="coach-msg bot">${reply}</div>`);log.scrollTop=log.scrollHeight}
}
function recordManualTechnique(id,detail){if(gameTechniques.has(id))return;gameTechniques.add(id);unlockTechnique(id);const base=difficultyScore[level],bonus=getTechniqueBonus(id,base);if(bonus){changePoints(bonus);gameScore+=bonus;flashScore(bonus);playCoinSound()}celebrateTechnique(id);setCoachHint(`技巧识别 · ${techniques[id].name}`,detail,{technique:id})}
function toggleNote(n){if(!selected||finished)return;const{r,c}=selected;if(puzzle[r][c]||values[r][c])return;const removing=notes[r][c].has(n),triple=removing?tripleForElimination(r,c,n):null;if(!removing&&noteConflicts(r,c,n)){showToast(lang==='en'?`Cannot mark ${n}: this row, column, or box already has it`:`这里不能标记 ${n}：同行、同列或九宫已有该数字`);return}replaceCellNotes(r,c,toggleCandidateSet(notes[r][c],n));setCellContent(getCell(r,c),r,c);getCell(r,c).setAttribute('aria-label',lang==='en'?`Row ${r+1}, column ${c+1}, candidates ${[...notes[r][c]].join(', ')||'none'}`:`第${r+1}行第${c+1}列，候选${[...notes[r][c]].join('、')||'无'}`);if(triple)recordManualTechnique('nakedTriple',lang==='en'?`You used candidates ${triple.digits.join(', ')} as a Naked Triple and removed candidate ${n} from row ${r+1}, column ${c+1}.`:`你利用候选 ${triple.digits.join('、')} 形成三数组，并从第 ${r+1} 行第 ${c+1} 列排除了候选 ${n}。`)}
function addContinuousNote(n){if(!selected||finished)return;const{r,c}=selected;if(puzzle[r][c]||values[r][c])return;const removing=notes[r][c].has(n);if(!removing&&noteConflicts(r,c,n)){showToast(lang==='en'?`Cannot mark ${n}: this row, column, or box already has it`:`这里不能标记 ${n}：同行、同列或九宫已有该数字`);return}replaceCellNotes(r,c,toggleCandidateSet(notes[r][c],n));setCellContent(getCell(r,c),r,c);getCell(r,c).setAttribute('aria-label',lang==='en'?`Row ${r+1}, column ${c+1}, candidates ${[...notes[r][c]].join(', ')||'none'}`:`第${r+1}行第${c+1}列，候选${[...notes[r][c]].join('、')||'无'}`)}
function updateSelectedPadNumber(){
  document.querySelectorAll('[data-number]').forEach(button=>button.classList.toggle('number-selected',selectedPadNumber===+button.dataset.number));
  document.querySelectorAll('.cell-notes i[data-note]').forEach(note=>note.classList.toggle('note-focus',selectedPadNumber===+note.dataset.note));
}
function updateActiveNoteNumber(){document.querySelectorAll('[data-number]').forEach(button=>button.classList.toggle('note-active',noteMode&&+button.dataset.number===activeNoteNumber));updateSelectedPadNumber()}
function removePeerNotes(r,c,n){const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let y=0;y<9;y++)for(let x=0;x<9;x++)if(!values[y][x]&&(y===r||x===c||(y>=br&&y<br+3&&x>=bc&&x<bc+3))&&notes[y][x].delete(n)){const cell=getCell(y,x);if(cell)setCellContent(cell,y,x)}}
function inputNumber(n,asHint=false){
  if(expressFinishing)return;if(!asHint)playNumberTone(n);selectedPadNumber=n;updateSelectedPadNumber();if(noteMode&&!asHint){if(noteInputMode==='cell'&&selected&&!values[selected.r][selected.c]){toggleNote(n);const marked=notes[selected.r][selected.c].has(n);showToast(lang==='en'?`${marked?'Marked':'Removed'} ${n} in the current cell`:`已在当前空格${marked?'标记':'取消'}数字 ${n}`)}else{noteInputMode='number';activeNoteNumber=n;selected=null;updateHighlights();updateActiveNoteNumber();showToast(lang==='en'?`Continuous note ${n}: tap cells to mark it`:`连续标记数字 ${n}：点击多个空格进行标记`)}return}if(!selected||finished)return;const {r,c}=selected;if(puzzle[r][c])return;
  const triple=n===solution[r][c]?tripleForPlacement(r,c,n):null,technique=n===solution[r][c]?(triple?'nakedTriple':detectTechnique(r,c,n)):null,moveReason=triple?(lang==='en'?`Candidates ${numList(triple.digits)} form a Naked Triple across three cells. After removing those candidates from this cell, only ${n} remains.`:`候选 ${numList(triple.digits)} 在三个格中形成三数组，从当前格排除这些候选后只剩 ${n}。`):technique==='nakedSingle'?explainNakedSingle(r,c,n):null;
  const cell=getCell(r,c),wasCorrect=values[r][c]===solution[r][c];cell.classList.remove('error');values[r][c]=n;cell.textContent=n;cell.classList.add('user');if(!asHint&&!wasCorrect){if(n===solution[r][c])rewardRhythm();else{correctStreak=0;updateJourney()}}
if(n!==solution[r][c]&&!asHint){playWrongSound();mistakes++;mistakesEl.textContent=`${mistakes}/3`;cell.classList.add('error');const penalty=difficultyScore[level]*2,actual=Math.min(profile.points,penalty),exceeded=mistakes>=3;changePoints(-actual);gameScore=Math.max(0,gameScore-actual);if(exceeded){finished=true;clearInterval(timerId);updateContinueButton();document.querySelector('#failPenalty').textContent=lang==='en'?`This mistake cost ${actual} points · Current points ${profile.points}`:`本次错误扣除 ${actual} 智慧点 · 当前积分 ${profile.points}`}setTimeout(()=>{if(values[r][c]===n){values[r][c]=0;cell.classList.remove('user','error');setCellContent(cell,r,c)}updateHighlights();updatePad();if(exceeded){document.querySelector('#failModal').hidden=false;playFailMusic()}},520)}
  else{notes[r][c].clear();removePeerNotes(r,c,n);if(asHint)cell.classList.add('hinted');if(technique)unlockTechnique(technique);if(!asHint){playCorrectSound();if(technique)gameTechniques.add(technique);const key=`${r}-${c}`;if(!scoredCells.has(key)){scoredCells.add(key);const base=difficultyScore[level],techniqueBonus=getTechniqueBonus(technique,base),gained=base+techniqueBonus;changePoints(gained);gameScore+=gained}showMoveFeedback(r,c,n,technique,moveReason);if(specialTechniqueIds.has(technique))celebrateTechnique(technique)}updateHighlights();updatePad();const isFinishing=!asHint&&finishLastNine();if(!isFinishing)checkComplete()}
}
function getTechniqueBonus(id,base){if(!id||basicTechniqueIds.has(id))return 0;const [min,max]=techniqueMultipliers[id]||[2,10],multiple=Math.floor(Math.random()*(max-min+1))+min;return base*multiple}
function celebrateTechnique(id){const t=techniques[id],el=document.querySelector('#applause');document.querySelector('#applauseTitle').textContent=lang==='en'?'👏 Great!':'👏 漂亮！';document.querySelector('#applauseText').textContent=lang==='en'?`You just used “${techniqueName(id)}”.`:`你刚刚运用了「${techniqueName(id)}」`;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');if(profile.soundEnabled)playApplause();setTimeout(()=>el.classList.remove('show'),2200)}
function playApplause(){try{const AudioCtx=window.AudioContext||window.webkitAudioContext,ctx=new AudioCtx();[0,.08,.16,.3,.38,.5].forEach((delay,i)=>{const length=Math.floor(ctx.sampleRate*.07),buffer=ctx.createBuffer(1,length,ctx.sampleRate),data=buffer.getChannelData(0);for(let j=0;j<length;j++)data[j]=(Math.random()*2-1)*Math.pow(1-j/length,2);const source=ctx.createBufferSource(),gain=ctx.createGain(),filter=ctx.createBiquadFilter();filter.type='bandpass';filter.frequency.value=900+i*110;gain.gain.setValueAtTime(.16,ctx.currentTime+delay);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+delay+.07);source.buffer=buffer;source.connect(filter).connect(gain).connect(ctx.destination);source.start(ctx.currentTime+delay)});setTimeout(()=>ctx.close(),1200)}catch{}}
function missingNumbers(list){return[1,2,3,4,5,6,7,8,9].filter(n=>!list.includes(n))}
function explainNakedSingle(r,c,n){const row=missingNumbers(values[r]),col=missingNumbers(values.map(line=>line[c])),br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3,box=[];for(let y=br;y<br+3;y++)for(let x=bc;x<bc+3;x++)box.push(values[y][x]);const boxMissing=missingNumbers(box);return lang==='en'?`The row is missing ${numList(row)}; the column is missing ${numList(col)}; the 3×3 box is missing ${numList(boxMissing)}. Their only shared candidate is ${n}.`:`本行缺 ${numList(row)}；本列缺 ${numList(col)}；本九宫缺 ${numList(boxMissing)}。三者共同候选只有 ${n}。`}
function showMoveFeedback(r,c,n,technique,moveReason=null){
  const card=document.querySelector('#learningHint'),title=document.querySelector('#hintTitle'),reason=document.querySelector('#hintReason');document.querySelectorAll('.cell.coached').forEach(el=>el.classList.remove('coached'));getCell(r,c).classList.add('coached');
  if(technique){setCoachHint(lang==='en'?`Step analysis · ${techniqueName(technique)}`:`本步解析 · ${techniqueName(technique)}`,lang==='en'?`Place ${n} in ${cellLabel(r,c)}. ${moveReason||techniqueDesc(technique)}`:`${cellLabel(r,c)}填入 ${n}。${moveReason||techniqueDesc(technique)}`,{r,c,n,technique})}
  else{setCoachHint(lang==='en'?'Step analysis · Basic elimination':'本步解析 · 基础排除',lang==='en'?`Place ${n} in ${cellLabel(r,c)}. This step did not match a named advanced technique; it mainly follows row, column, and box elimination.`:`${cellLabel(r,c)}填入 ${n}。这一步没有匹配到特定进阶技巧，主要依据同行、同列与宫内数字进行综合排除。`,{r,c,n})}
  card.hidden=false;
}
function erase(){if(expressFinishing||!selected||finished)return;const{r,c}=selected;if(puzzle[r][c])return;const cell=getCell(r,c);if(!values[r][c]&&notes[r][c].size){notes[r][c].clear();setCellContent(cell,r,c);playEraseSound();showToast(lang==='en'?'Candidate notes erased':'已擦除候选标记');return}values[r][c]=0;cell.classList.remove('user','error','hinted');setCellContent(cell,r,c);playEraseSound();updateHighlights();updatePad()}
function fillAllCandidateNotes(){if(finished||expressFinishing)return;const cost=autoNotesCost[level];if(!cost){showToast(lang==='en'?'Auto notes unlock at Advanced puzzles':'一键标记需要高级局解锁');return}if(profile.points<cost){showToast(lang==='en'?`Not enough points: auto notes need ${cost}`:`积分不足：一键标记需要 ${cost} 分`);return}let cells=0,candidates=0;for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(!values[r][c]){const options=candidatesAt(r,c);notes[r][c]=new Set(options);cells++;candidates+=options.length;setCellContent(getCell(r,c),r,c)}changePoints(-cost);gameScore=Math.max(0,gameScore-cost);playAutoNotesSound();showToast(lang==='en'?`Marked ${cells} cells and ${candidates} candidates · -${cost} points`:`已标记 ${cells} 个空格、${candidates} 个候选 · 扣 ${cost} 分`)}
function useHint(){
  if(finished||expressFinishing)return;if(!hints){showToast('本局的提示已经用完啦');return}const advancedTeaching=levelOrder.indexOf(level)>=2,cost=autoNotesCost[level]||difficultyScore[level]*2;if(profile.points<cost){showToast(`${advancedTeaching?'技巧教学':'提示'}需要 ${cost} 积分`);return}if(selectedRouteTechnique){useSelectedTechniqueHint(cost);return}
  let target=selected&&values[selected.r][selected.c]!==solution[selected.r][selected.c]?selected:null;
  if(!target){const empty=[];for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(values[r][c]!==solution[r][c])empty.push({r,c});if(advancedTeaching)target=empty.find(p=>specialTechniqueIds.has(detectTechnique(p.r,p.c,solution[p.r][p.c])));target=target||empty.sort((a,b)=>candidatesAt(a.r,a.c).length-candidatesAt(b.r,b.c).length)[0]}
  if(!target)return;playHintSound();changePoints(-cost);gameScore=Math.max(0,gameScore-cost);selected=target;hints--;document.querySelector('#hintCount').textContent=hints;const technique=advancedTeaching?showKingTeachingHint(target.r,target.c):showLearningHint(target.r,target.c);if(technique)unlockTechnique(technique);updateHighlights();showToast(`${advancedTeaching?'王者高级教学':'提示'} · 扣 ${cost} 积分`)
}
function useSelectedTechniqueHint(cost){playHintSound();changePoints(-cost);gameScore=Math.max(0,gameScore-cost);hints--;document.querySelector('#hintCount').textContent=hints;document.querySelectorAll('.cell.coached').forEach(cell=>cell.classList.remove('coached'));const name=selectedRouteTechnique,techniqueId=routeTechniqueIds[name],target=findLessonTarget(name),lesson=lang==='en'?(techniqueDesc(techniqueId)||'Observe candidate restrictions and find a removable candidate.'):(techniqueLessons[name]||'观察候选之间的限制关系，找到可以排除的数字。'),displayName=routeLabel(name);if(target){selected={r:target.r,c:target.c};(target.cells||[target]).forEach(p=>getCell(p.r,p.c)?.classList.add('coached'));setCoachHint(lang==='en'?`Technique lesson · ${displayName}`:`技巧教学 · ${displayName}`,target.detail?`${lang==='en'?'How to use it:':'使用方法：'}${lesson} ${target.detail}`:(lang==='en'?`How to use it: ${lesson} The current board is ready for this technique. Focus on ${cellLabel(target.r,target.c)} and its related units.`:`使用方法：${lesson} 当前棋盘已经具备使用条件，请重点观察${cellLabel(target.r,target.c)}及其相关区域。`),{r:target.r,c:target.c,technique:techniqueId,route:name});if(techniqueId){gameTechniques.add(techniqueId);unlockTechnique(techniqueId);if(!basicTechniqueIds.has(techniqueId))celebrateTechnique(techniqueId)}}else setCoachHint(lang==='en'?`Technique lesson · ${displayName}`:`技巧教学 · ${displayName}`,lang==='en'?`How to use it: ${lesson} This position is not ready for “${displayName}” yet. Continue with other eliminations first.`:`使用方法：${lesson} 当前局面还不够条件使用「${displayName}」，请先继续完成其他排除。`,{route:name});updateHighlights();(target?.cells||[]).forEach(p=>getCell(p.r,p.c)?.classList.add('coached'));showToast(lang==='en'?`${displayName} lesson · -${cost} points`:`「${displayName}」教学 · 扣 ${cost} 分`)}
function findLessonTarget(name){const detector=lessonDetectorIds[name];if(detector)for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(!values[r][c]&&detectTechnique(r,c,solution[r][c])===detector)return{r,c};const units=[];for(let i=0;i<9;i++){units.push([...Array(9)].map((_,c)=>({r:i,c})));units.push([...Array(9)].map((_,r)=>({r,c:i})));units.push([...Array(9)].map((_,k)=>({r:Math.floor(i/3)*3+Math.floor(k/3),c:(i%3)*3+k%3})))}if(name==='隐性数对')for(const unit of units)for(let a=1;a<=8;a++)for(let b=a+1;b<=9;b++){const pa=unit.filter(p=>!values[p.r][p.c]&&candidatesAt(p.r,p.c).includes(a)),pb=unit.filter(p=>!values[p.r][p.c]&&candidatesAt(p.r,p.c).includes(b));if(pa.length===2&&pb.length===2&&pa.every((p,i)=>p.r===pb[i].r&&p.c===pb[i].c)){const cells=pa,removed=cells.map(p=>candidatesAt(p.r,p.c).filter(n=>n!==a&&n!==b));return{...cells[0],cells,detail:lang==='en'?`The hidden pair is ${a} and ${b}. Both digits can appear only in ${cellLabel(cells[0].r,cells[0].c)} and ${cellLabel(cells[1].r,cells[1].c)}. Keep only ${a}, ${b} in those two cells; remove ${numList(removed[0])} and ${numList(removed[1])} respectively.`:`当前形成隐性数对的是数字 ${a}、${b}，它们都只能出现在${cellLabel(cells[0].r,cells[0].c)}和${cellLabel(cells[1].r,cells[1].c)}。因此两格只保留 ${a}、${b}；分别排除 ${numList(removed[0])} 和 ${numList(removed[1])}。`}}}if(name==='三数组')for(const unit of units){const cells=unit.filter(p=>!values[p.r][p.c]&&candidatesAt(p.r,p.c).length>=2&&candidatesAt(p.r,p.c).length<=3);for(let a=0;a<cells.length-2;a++)for(let b=a+1;b<cells.length-1;b++)for(let c=b+1;c<cells.length;c++){const union=new Set([...candidatesAt(cells[a].r,cells[a].c),...candidatesAt(cells[b].r,cells[b].c),...candidatesAt(cells[c].r,cells[c].c)]);if(union.size===3)return cells[a]}}if(name==='X-Wing')for(let n=1;n<=9;n++){const rows=[];for(let r=0;r<9;r++){const cols=[];for(let c=0;c<9;c++)if(!values[r][c]&&candidatesAt(r,c).includes(n))cols.push(c);if(cols.length===2)rows.push({r,cols})}for(let a=0;a<rows.length-1;a++)for(let b=a+1;b<rows.length;b++)if(rows[a].cols.join()===rows[b].cols.join()){const remove=[];for(let r=0;r<9;r++)if(r!==rows[a].r&&r!==rows[b].r)for(const c of rows[a].cols)if(!values[r][c]&&candidatesAt(r,c).includes(n))remove.push({r,c});if(remove.length){const cells=[...rows[a].cols.map(c=>({r:rows[a].r,c})),...rows[b].cols.map(c=>({r:rows[b].r,c})),...remove];return{...cells[0],cells,detail:lang==='en'?`Digit ${n} appears only in columns ${rows[a].cols[0]+1} and ${rows[a].cols[1]+1} in rows ${rows[a].r+1} and ${rows[b].r+1}, forming the four X-Wing corners. Remove candidate ${n} from the other cells in those two columns: ${remove.map(p=>shortCellLabel(p.r,p.c)).join(', ')}.`:`数字 ${n} 在第 ${rows[a].r+1}、${rows[b].r+1} 行中都只出现在第 ${rows[a].cols[0]+1}、${rows[a].cols[1]+1} 列，形成四个角。因此可从这两列的其他位置删除候选 ${n}：${remove.map(p=>shortCellLabel(p.r,p.c)).join('、')}。`}}}}return null}
function showKingTeachingHint(r,c){
  const answer=solution[r][c],candidates=candidatesAt(r,c),technique=detectTechnique(r,c,answer),isSpecial=specialTechniqueIds.has(technique),route=advancedRoutes.king[(2-hints+advancedRoutes.king.length)%advancedRoutes.king.length],name=isSpecial?techniqueName(technique):routeLabel(route),canReveal=technique==='bugPlusOne';
  document.querySelectorAll('.cell.coached').forEach(cell=>cell.classList.remove('coached'));getCell(r,c).classList.add('coached');
  if(canReveal)setCoachHint(lang==='en'?`Master teaching · ${name}`:`王者教学 · ${name}`,lang==='en'?`The position forms BUG+1: all other unsolved cells are bivalue, and only this cell is trivalue. By candidate parity, ${cellLabel(r,c)} should be ${answer}.`:`当前局面形成 BUG+1：其他未定格均为双值，只有这一格是三值。按候选出现次数的奇偶规律，可以确定${cellLabel(r,c)}应填 ${answer}。`,{r,c,n:answer,technique});
  else if(isSpecial)setCoachHint(lang==='en'?`Master teaching · ${name}`:`王者教学 · ${name}`,lang==='en'?`First use “${name}” to continue eliminating. Candidates in this cell: ${numList(candidates)}. ${techniqueDesc(technique)} After the elimination, check whether a single value is formed.`:`先运用「${name}」继续排除。当前格候选为 ${numList(candidates)}；${techniqueDesc(technique)} 完成排除后，再判断是否形成唯一数字。`,{r,c,technique});
  else setCoachHint(lang==='en'?`Master teaching · ${name}`:`王者教学 · ${name}`,lang==='en'?`Candidates in this cell: ${numList(candidates)}. This step suggests looking for a “${name}” pattern first. It is not ready to reveal a final digit yet.`:`当前格候选为 ${numList(candidates)}。本步建议先寻找「${name}」结构进行排除；尚未形成可直接定值的模式，所以暂不公布答案。`,{r,c,route});
  return isSpecial?technique:null;
}
function candidatesAt(r,c){if(values[r][c]===solution[r][c])return[];const used=new Set([...values[r],...values.map(row=>row[c])]);const rr=Math.floor(r/3)*3,cc=Math.floor(c/3)*3;for(let y=rr;y<rr+3;y++)for(let x=cc;x<cc+3;x++)used.add(values[y][x]);return[1,2,3,4,5,6,7,8,9].filter(n=>!used.has(n))}
function showLearningHint(r,c){
  const answer=solution[r][c],candidates=candidatesAt(r,c),units=[
    {name:lang==='en'?`row ${r+1}`:`第 ${r+1} 行`,cells:[...Array(9)].map((_,x)=>({r,c:x}))},
    {name:lang==='en'?`column ${c+1}`:`第 ${c+1} 列`,cells:[...Array(9)].map((_,y)=>({r:y,c}))},
    {name:lang==='en'?'the 3×3 box':'所在的 3×3 宫',cells:[...Array(9)].map((_,i)=>({r:Math.floor(r/3)*3+Math.floor(i/3),c:Math.floor(c/3)*3+i%3}))}
  ];
  const hiddenSingle=units.find(unit=>unit.cells.filter(p=>!values[p.r][p.c]&&candidatesAt(p.r,p.c).includes(answer)).length===1);
  let technique=detectTechnique(r,c,answer),reason,canReveal=technique==='bugPlusOne'||candidates.length===1||Boolean(hiddenSingle);if(technique==='bugPlusOne')reason=lang==='en'?`This is BUG+1: all other unsolved cells have two candidates, while this cell has three. Candidate parity shows the extra candidate ${answer} must go here.`:`这是“全双值坟墓（BUG+1）”：其他未定格都只有两个候选，唯独此格有三个。按候选出现次数的奇偶规律，额外候选 ${answer} 必须填在这里。`;
  else if(candidates.length===1)reason=lang==='en'?`Check the row, column, and box: every other digit conflicts, so the only candidate is ${answer}.`:`观察同行、同列和所在宫，其他数字都已产生冲突，因此唯一候选是 ${answer}。`;
  else if(hiddenSingle)reason=lang==='en'?`In ${hiddenSingle.name}, placing ${answer} in any other empty cell would conflict with existing digits, so it can only go here.`:`在${hiddenSingle.name}里，数字 ${answer} 放到其他空格都会与已有数字冲突，所以它只能放在这里。`;
  else reason=lang==='en'?`This cell currently has candidates ${numList(candidates)}. It cannot be uniquely solved yet. Continue checking where these candidates can appear in the row, column, and box.`:`这一格目前的候选数字是 ${numList(candidates)}，暂时还不能唯一确定。继续观察这些候选在同行、同列和九宫中的位置。`;
  document.querySelectorAll('.cell.coached').forEach(cell=>cell.classList.remove('coached'));getCell(r,c).classList.add('coached');
  setCoachHint(canReveal?(lang==='en'?`${cellLabel(r,c)} should be ${answer}`:`${cellLabel(r,c)}，应填 ${answer}`):(lang==='en'?`${cellLabel(r,c)}, candidates ${numList(candidates)}`:`${cellLabel(r,c)}，候选 ${numList(candidates)}`),reason,{r,c,n:canReveal?answer:null,technique});
  return technique;
}
function detectTechnique(r,c,n){
  const candidates=candidatesAt(r,c);if(isBugPlusOne(r,c,n))return'bugPlusOne';
  const units=getUnits(r,c),hidden=units.some(unit=>unit.filter(p=>!values[p.r][p.c]&&candidatesAt(p.r,p.c).includes(n)).length===1);
  if(candidates.length===1)return'nakedSingle';if(hidden)return'hiddenSingle';return null;
}
function getUnits(r,c){return[[...Array(9)].map((_,x)=>({r,c:x})),[...Array(9)].map((_,y)=>({r:y,c})),[...Array(9)].map((_,i)=>({r:Math.floor(r/3)*3+Math.floor(i/3),c:Math.floor(c/3)*3+i%3}))]}
function hasNakedPair(unit,r,c){const mine=candidatesAt(r,c);if(mine.length!==2)return false;return unit.some(p=>(p.r!==r||p.c!==c)&&!values[p.r][p.c]&&candidatesAt(p.r,p.c).join('')===mine.join(''))}
function hasLockedCandidate(n,r,c){const box=getUnits(r,c)[2].filter(p=>!values[p.r][p.c]&&candidatesAt(p.r,p.c).includes(n));return box.length>1&&(box.every(p=>p.r===box[0].r)||box.every(p=>p.c===box[0].c))}
function isBugPlusOne(r,c,n){const empty=[];for(let y=0;y<9;y++)for(let x=0;x<9;x++)if(!values[y][x])empty.push({r:y,c:x,opts:candidatesAt(y,x)});const triples=empty.filter(p=>p.opts.length===3);if(triples.length!==1||triples[0].r!==r||triples[0].c!==c||empty.some(p=>p.opts.length!==2&&p.opts.length!==3))return false;return getUnits(r,c).every(unit=>unit.reduce((sum,p)=>sum+(!values[p.r][p.c]&&candidatesAt(p.r,p.c).includes(n)?1:0),0)%2===1)}
function grantFeatureRewards(){const awarded=[];for(const feature of featureMilestones)if(profile.rankIndex>=feature.rankIndex&&!profile.featureRewards.includes(feature.id)){profile.featureRewards.push(feature.id);profile.points+=feature.points;awarded.push(`${feature.name} +${feature.points} 分`)}return awarded}
function checkRankPromotion(){const before=profile.rankIndex,after=rankIndexFromPoints();if(after>before)return`积分达标，自动晋级为${ranks[after].name}`;return''}
function recordCompletedGame(){const oldTime=profile.bestTimes[level],oldScore=profile.highScores[level]||0,newBestTime=!oldTime||seconds<oldTime;let reward=0,timeBonusAmount=0,scoreBonusAmount=0;if(newBestTime&&gameScore>0){timeBonusAmount=gameScore;reward+=timeBonusAmount;profile.points+=timeBonusAmount;gameScore*=2}const newHighScore=gameScore>oldScore;if(newHighScore&&gameScore>0){scoreBonusAmount=gameScore;reward+=scoreBonusAmount;profile.points+=scoreBonusAmount;gameScore*=2}profile.gamesCompleted[level]=(profile.gamesCompleted[level]||0)+1;if(newBestTime)profile.bestTimes[level]=seconds;if(newHighScore)profile.highScores[level]=gameScore;let trialPromotion='',trialPromotionEn='';if(currentGameIsTrial){const target=ranks[levelOrder.indexOf(level)],targetLevel=levelOrder[levelOrder.indexOf(level)],qualified=seconds<playerBenchmarks[level].average;profile.trialWinStreaks[target.name]=(profile.trialWinStreaks[target.name]||0)+1;if(qualified)profile.trialFastWins[target.name]=(profile.trialFastWins[target.name]||0)+1;const streak=profile.trialWinStreaks[target.name],fast=profile.trialFastWins[target.name]||0;if(streak>=3||fast>=3){profile.points=Math.max(profile.points,target.min);profile.trialWinStreaks[target.name]=0;profile.trialFastWins[target.name]=0;trialPromotion=`越级挑战达标，晋级为${target.name}`;trialPromotionEn=`Challenge cleared: promoted to ${levelLabel(targetLevel)}`}}saveProfile();if(reward){flashScore(reward);playCoinSound();playJoyMelody()}return{newBestTime,newHighScore,reward,timeBonusAmount,scoreBonusAmount,trialPromotion,trialPromotionEn}}
function completionStatusText(record,beforeRank){if(record?.trialPromotion)return lang==='en'?record.trialPromotionEn:record.trialPromotion;if(profile.rankIndex>beforeRank)return lang==='en'?`Point goal reached: promoted to ${levelLabel(levelOrder[profile.rankIndex])}`:`积分达标，自动晋级为${ranks[profile.rankIndex].name}`;return''}
function checkComplete(){if(values.flat().every(Boolean)&&values.every((row,r)=>row.every((n,c)=>n===solution[r][c]))){finished=true;clearInterval(timerId);let status='';if(!completionAwarded){completionAwarded=true;const beforeRank=profile.rankIndex;completionRecord=recordCompletedGame();status=completionStatusText(completionRecord,beforeRank);showToast(completionRecord.reward?(lang==='en'?'New record! This game score was doubled.':'刷新纪录，当局得分已翻倍'):(lang==='en'?'Nice, puzzle completed!':'漂亮，完成本局！'))}document.querySelector('#modalTitle').dataset.rankStatus=status;setTimeout(showComplete,250)}}
function getPlayerComparison(time){const benchmark=playerBenchmarks[level],z=(benchmark.average-time)/benchmark.spread,percent=Math.max(1,Math.min(99,Math.round(100/(1+Math.exp(-1.7*z)))));return{average:benchmark.average,percent}}
function showComplete(){document.querySelector('#resultLevel').textContent=levelLabel(level);document.querySelector('#resultTime').textContent=formatTime(seconds);document.querySelector('#resultMistakes').textContent=mistakes;document.querySelector('#resultScore').textContent=gameScore;const comparison=getPlayerComparison(seconds),used=[...gameTechniques].map(id=>techniqueName(id)).filter(Boolean),usedText=used.length?used.join(lang==='en'?', ':'、'):T('basic');document.querySelector('#playerComparison').innerHTML=lang==='en'?`<small>${levelLabel(level)} ${T('avgTime')} <b>${formatTime(comparison.average)}</b></small><strong>${T('beat')} <em>${comparison.percent}%</em> ${T('sameLevelPlayers')}</strong><strong class="used-techniques">${T('usedTech')} ${usedText} ${T('techniqueWord')}</strong><span>${T('localData')}</span>`:`<small>${levelNames[level]}玩家平均用时 <b>${formatTime(comparison.average)}</b></small><strong>你超过了 <em>${comparison.percent}%</em> 的同级玩家</strong><strong class="used-techniques">你使用了 ${usedText} 技巧</strong><span>当前为本地参考数据</span>`;const awards=document.querySelector('#resultAwards'),items=[];if(completionRecord?.newBestTime)items.push(lang==='en'?`<span>✦ New best time: score doubled <b class="record-bonus">+${completionRecord.timeBonusAmount} pts</b></span>`:`<span>✦ 新最佳时间：当局得分翻倍 <b class="record-bonus">+${completionRecord.timeBonusAmount} 分</b></span>`);if(completionRecord?.newHighScore)items.push(lang==='en'?`<span>✦ New high score: score doubled again <b class="record-bonus">+${completionRecord.scoreBonusAmount} pts</b></span>`:`<span>✦ 新最高得分：当局得分再次翻倍 <b class="record-bonus">+${completionRecord.scoreBonusAmount} 分</b></span>`);if(completionRecord?.trialPromotion)items.push(`<span>♛ ${lang==='en'?completionRecord.trialPromotionEn:completionRecord.trialPromotion}</span>`);awards.innerHTML=items.join('');awards.hidden=!items.length;const status=document.querySelector('#modalTitle').dataset.rankStatus;if(status)showToast(status);document.querySelector('#modal').hidden=false;if(Date.now()-lastFinalRunAt>4200)playVictoryMusic()}
function removeCompletedNumberNotes(n){if(!notes.length)return;for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(notes[r][c].delete(n)&&!values[r][c]){const cell=getCell(r,c);if(cell)setCellContent(cell,r,c)}}
function updatePad(){for(let n=1;n<=9;n++){const count=values.flat().filter(v=>v===n).length,remaining=9-count,button=document.querySelector(`[data-number="${n}"]`);button.querySelector('small').textContent=remaining;button.setAttribute('aria-label',lang==='en'?`Number ${n}, ${remaining} remaining`:`数字${n}，还剩${remaining}个`);button.classList.toggle('complete',remaining===0);if(remaining===0)removeCompletedNumberNotes(n)}updateExpressReminder()}
function updateExpressReminder(){document.querySelectorAll('.cell.express-ready').forEach(cell=>cell.classList.remove('express-ready'));if(levelOrder.indexOf(level)<2||!profile.expressEnabled||finished)return;for(let n=1;n<=9;n++)if(values.flat().filter(value=>value===n).length===8)for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(!values[r][c]&&solution[r][c]===n){const cell=getCell(r,c);cell.classList.add('express-ready');cell.setAttribute('aria-label',lang==='en'?`Express fill reminder: last position for ${n}`:`快速填充提醒：数字${n}的最后位置`)}}
function getCell(r,c){return document.querySelector(`.cell[data-r="${r}"][data-c="${c}"]`)}
function tick(){if(!finished){seconds++;timerEl.textContent=formatTime(seconds);if(levelOrder.indexOf(level)===profile.rankIndex){profile.playSeconds[profile.rankIndex]++;if(seconds%10===0){localStorage.setItem('sudoku-profile-v1',JSON.stringify(profile));updateDifficultyAccess()}}}}
function formatTime(s){return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function showToast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}

document.querySelectorAll('.difficulty button').forEach(btn=>btn.addEventListener('click',()=>{if(expressFinishing)return;const i=levelOrder.indexOf(btn.dataset.level),status=trialEligibility(i);if(!status.eligible){showToast(status.reason);return}if(btn.dataset.level===level)return;level=btn.dataset.level;document.querySelectorAll('.difficulty button').forEach(b=>b.classList.toggle('active',b===btn));newGame()}));
document.querySelectorAll('[data-number]').forEach(btn=>btn.addEventListener('click',()=>inputNumber(+btn.dataset.number)));
document.querySelector('#eraseButton').addEventListener('click',erase);document.querySelector('#hintButton').addEventListener('click',useHint);document.querySelector('#newButton').addEventListener('click',()=>{if(expressFinishing)return;const status=trialEligibility(levelOrder.indexOf(level));if(!status.eligible){selectDefaultLevel();showToast(status.reason);return}newGame()});
document.querySelector('#coachQuick').addEventListener('click',e=>{const button=e.target.closest('[data-coach-question]');if(!button)return;coachReply(button.dataset.coachQuestion)});
document.querySelector('#coachForm').addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#coachInput'),text=input.value.trim();if(!text)return;coachReply('custom',text);input.value=''});
function toggleNoteMode(){if(expressFinishing)return;noteMode=!noteMode;activeNoteNumber=null;if(noteMode)noteInputMode=selected&&!values[selected.r][selected.c]?'cell':null;else noteInputMode=null;const button=document.querySelector('#notesButton');button.classList.toggle('active',noteMode);button.setAttribute('aria-pressed',String(noteMode));updateHighlights();updateActiveNoteNumber();showToast(noteMode?(noteInputMode==='cell'?(lang==='en'?'Notes on: choose multiple numbers for this cell':'标记已开启：可为当前空格连续选择多个数字'):(lang==='en'?'Notes on: tap a cell or a number first':'标记已开启：先点空格或先点数字均可')):(lang==='en'?'Candidate notes off':'候选标记已关闭'))}
document.querySelector('#notesButton').addEventListener('click',toggleNoteMode);
document.querySelector('#autoNotesButton').addEventListener('click',fillAllCandidateNotes);
document.querySelector('#techniqueRouteText').addEventListener('click',e=>{const button=e.target.closest('[data-route-technique]');if(!button)return;selectedRouteTechnique=button.dataset.routeTechnique;updateTechniqueRoute();showToast(`已选择「${selectedRouteTechnique}」，点击提示查看教学`) });
document.querySelector('#againButton').addEventListener('click',()=>{document.querySelector('#modal').hidden=true;selectDefaultLevel();newGame()});document.querySelector('#closeModal').addEventListener('click',()=>document.querySelector('#modal').hidden=true);
function localDateKey(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function registerDailyFailure(){const today=localDateKey();if(profile.dailyFailures.date!==today)profile.dailyFailures={date:today,counts:{}};if(currentGameIsTrial){const target=ranks[levelOrder.indexOf(level)];profile.trialWinStreaks[target.name]=0;saveProfile();return null}const rankLevel=levelOrder[profile.rankIndex];if(level!==rankLevel||profile.rankIndex===0){saveProfile();return null}const count=(profile.dailyFailures.counts[level]||0)+1,limit=level==='legend'?3:10;profile.dailyFailures.counts[level]=count;if(count<limit){saveProfile();return{text:lang==='en'?`Today’s failures ${count}/${limit}`:`今日失败 ${count}/${limit}`,demoted:false}};const oldRank=profile.rankIndex,newRank=Math.max(0,oldRank-1);profile.points=Math.min(profile.points,ranks[oldRank].min-1);profile.dailyFailures.counts[level]=0;saveProfile();return{text:lang==='en'?`You failed ${limit} times today and were demoted to ${levelLabel(levelOrder[newRank])}.`:`今日累计失败 ${limit} 局，已降级为${ranks[newRank].name}`,demoted:true}}
document.querySelector('#restartAfterFail').addEventListener('click',()=>{document.querySelector('#failModal').hidden=true;const result=registerDailyFailure();if(result?.demoted){document.querySelector('#streakFailText').textContent=result.text;document.querySelector('#demoteAndRestart').textContent=lang==='en'?'Restart at new rank':'按新等级重新开始';document.querySelector('#streakFailModal').hidden=false;return}if(result)showToast(result.text);selectDefaultLevel();newGame()});
document.querySelector('#demoteAndRestart').addEventListener('click',()=>{document.querySelector('#streakFailModal').hidden=true;selectDefaultLevel();newGame()});
document.querySelector('#continueWithPoints').addEventListener('click',()=>{const cost=continueCost[level];if(profile.points<cost)return;changePoints(-cost);gameScore=Math.max(0,gameScore-cost);mistakes=0;mistakesEl.textContent='0/3';finished=false;document.querySelector('#failModal').hidden=true;timerId=setInterval(tick,1000);showToast(lang==='en'?`Spent ${cost} points. Continue this puzzle.`:`已扣除 ${cost} 积分，继续本局`)});
document.querySelector('#themeButton').addEventListener('click',()=>{document.documentElement.classList.toggle('dark');localStorage.setItem('sudoku-theme',document.documentElement.classList.contains('dark')?'dark':'light')});
document.querySelector('#langButton').addEventListener('click',()=>{lang=lang==='en'?'zh':'en';localStorage.setItem('sudoku-lang',lang);const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState(null,'',url);applyLanguage();showToast(lang==='en'?'Language: English':'语言：中文')});
function openProfile(){renderProfile();document.querySelector('#profileModal').hidden=false}
document.querySelector('#profileButton').addEventListener('click',openProfile);document.querySelector('#brandProfileButton').addEventListener('click',openProfile);document.querySelector('#closeProfile').addEventListener('click',()=>document.querySelector('#profileModal').hidden=true);document.querySelector('#claimReward').addEventListener('click',()=>{if(pendingBadge&&!profile.badges.includes(pendingBadge)){profile.badges.push(pendingBadge);saveProfile()}pendingBadge=null;document.querySelector('#rewardModal').hidden=true});
document.addEventListener('click',e=>{const badge=e.target.closest?.('[data-technique]');if(badge){e.preventDefault();showTechniqueDetails(badge.dataset.technique)}});document.querySelector('#badgeCount').closest('span').classList.add('clickable-stat');document.querySelector('#badgeCount').closest('span').addEventListener('click',()=>{const id=Object.keys(techniques).sort((a,b)=>(profile.techniqueUses[b]||0)-(profile.techniqueUses[a]||0))[0];showTechniqueDetails(id)});document.querySelector('#closeTechnique').addEventListener('click',()=>document.querySelector('#techniqueModal').hidden=true);
const profileTitleEl=document.querySelector('#profileTitle'),playerNameInput=document.querySelector('#playerName');
function beginNameEdit(){profileTitleEl.hidden=true;playerNameInput.hidden=false;playerNameInput.value=displayPlayerName();playerNameInput.focus();playerNameInput.select()}
function finishNameEdit(save=true){if(playerNameInput.hidden)return;if(save){const value=playerNameInput.value.trim();profile.name=!value||value==='Sudoku Rookie'||value==='数独新手'?'数独新手':value}playerNameInput.hidden=true;profileTitleEl.hidden=false;saveProfile()}
profileTitleEl.addEventListener('click',beginNameEdit);profileTitleEl.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();beginNameEdit()}});playerNameInput.addEventListener('blur',()=>finishNameEdit(true));playerNameInput.addEventListener('keydown',e=>{if(e.key==='Enter')playerNameInput.blur();else if(e.key==='Escape'){playerNameInput.value=profile.name;finishNameEdit(false)}});
document.querySelector('#avatarPicker').addEventListener('click',e=>{const button=e.target.closest('[data-avatar]');if(!button)return;profile.avatar=button.dataset.avatar;saveProfile()});
document.querySelector('#randomAvatar').addEventListener('click',()=>{const colors=['#6f8062','#58788f','#9a6e62','#7b6b9b','#a17d3f','#477b73'];profile.avatar=avatars[Math.floor(Math.random()*avatars.length)];profile.avatarColor=colors[Math.floor(Math.random()*colors.length)];saveProfile();showToast(lang==='en'?'Random avatar created':'已随机生成个人图案')});
document.querySelector('#saveCustomAvatar').addEventListener('click',()=>{const text=document.querySelector('#customAvatarText').value.trim();if(!text){showToast(lang==='en'?'Please enter 1–2 characters first':'请先输入 1～2 个字符');return}profile.avatar=text;profile.avatarColor=document.querySelector('#customAvatarColor').value;saveProfile();showToast(lang==='en'?'Avatar updated':'个人图案已更新')});
document.querySelector('#avatarPhoto').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{const size=Math.min(image.width,image.height),sx=(image.width-size)/2,sy=(image.height-size)/2,canvas=document.createElement('canvas');canvas.width=160;canvas.height=160;canvas.getContext('2d').drawImage(image,sx,sy,size,size,0,0,160,160);profile.avatar=canvas.toDataURL('image/jpeg',.78);URL.revokeObjectURL(url);saveProfile();showToast(lang==='en'?'Photo avatar saved locally':'照片头像已保存到本机');e.target.value=''};image.onerror=()=>{URL.revokeObjectURL(url);showToast(lang==='en'?'Could not read this photo':'无法读取这张照片')};image.src=url});
document.querySelector('#expressToggle').addEventListener('change',e=>{profile.expressEnabled=e.target.checked;saveProfile();updateExpressReminder();showToast(e.target.checked?(lang==='en'?'Express fill on':'快速填充已开启'):(lang==='en'?'Express fill off':'快速填充已关闭'))});
function updateSoundButton(){const button=document.querySelector('#soundToggle');button.textContent=profile.soundEnabled?'♪':'×';button.classList.toggle('muted',!profile.soundEnabled);button.title=profile.soundEnabled?(lang==='en'?'Reward music on':'奖励音乐已开启'):(lang==='en'?'Reward music off':'奖励音乐已关闭');updateSoundUnlock()}
document.querySelector('#soundUnlock').addEventListener('click',primeAudio);
document.querySelector('#soundToggle').addEventListener('click',()=>{profile.soundEnabled=!profile.soundEnabled;if(!profile.soundEnabled)soundUnlocked=false;localStorage.setItem('sudoku-profile-v1',JSON.stringify(profile));updateSoundButton();if(profile.soundEnabled)primeAudio();else showToast(lang==='en'?'Reward music off':'奖励音乐已关闭')});updateSoundButton();
document.addEventListener('keydown',e=>{if(/^[1-9]$/.test(e.key))inputNumber(+e.key);else if(['Backspace','Delete','0'].includes(e.key))erase();else if(selected&&e.key.startsWith('Arrow')){e.preventDefault();const d={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]}[e.key];select((selected.r+d[0]+9)%9,(selected.c+d[1]+9)%9)}});
if(localStorage.getItem('sudoku-theme')==='dark')document.documentElement.classList.add('dark');saveProfile();applyLanguage();selectDefaultLevel();newGame();
